/*
 * Automat.cpp
 *
 *  Created on: 27.03.2016
 *      Author: Manuel
 */

#include "Automat.h"
#include <iostream>

Automat::Automat() {
	// TODO Auto-generated constructor stub
	this->initTransitionTable();
	this->currentState = INIT;
}

Automat::~Automat() {
	// TODO Auto-generated destructor stub
}

uint16_t Automat::getStateByChar(char currentChar) {
	return transitionTable[this->currentState][this->getCharacterType(currentChar)];
}

uint16_t Automat::testChar(char currentChar) {
	this->currentState = transitionTable[this->currentState][this->getCharacterType(currentChar)];

	return this->currentState;
}

uint16_t Automat::setTokenState() {
	this->currentState = TOKEN;

	return this->currentState;
}

uint16_t Automat::getCharacterType(char currentChar) {
	if (currentChar >= '0' && currentChar <= '9') {
		return CT_DIGIT;
	} else if ( ((currentChar >= 'A') && (currentChar <= 'D')) ||
				(currentChar == 'G') ||
				((currentChar >= 'J') && (currentChar <= 'K')) ||
				((currentChar >= 'M') && (currentChar <= 'V')) ||
				((currentChar >= 'X') && (currentChar <= 'Z')) ||

				((currentChar >= 'a') && (currentChar <= 'd')) ||
				(currentChar == 'g') ||
				((currentChar >= 'j') && (currentChar <= 'k')) ||
				((currentChar >= 'm') && (currentChar <= 'v')) ||
				((currentChar >= 'x') && (currentChar <= 'z'))) {
		return CT_LETTER;
	} else if ( currentChar == 'i') {
		return CT_SMALL_I;
	} else if ( currentChar == 'f') {
		return CT_SMALL_F;
	} else if ( currentChar == 'w') {
		return CT_SMALL_W;
	} else if ( currentChar == 'h') {
		return CT_SMALL_H;
	} else if ( currentChar == 'l') {
		return CT_SMALL_L;
	} else if ( currentChar == 'e') {
		return CT_SMALL_E;
	} else if ( currentChar == 'I') {
		return CT_CAPITAL_I;
	} else if ( currentChar == 'F') {
		return CT_CAPITAL_F;
	} else if ( currentChar == 'W') {
		return CT_CAPITAL_W;
	} else if ( currentChar == 'H') {
		return CT_CAPITAL_H;
	} else if ( currentChar == 'L') {
		return CT_CAPITAL_L;
	} else if ( currentChar == 'E') {
		return CT_CAPITAL_E;
	} else if ( currentChar == 'r') {
		return CT_SMALL_R;
	} else if ( currentChar == 'R') {
		return CT_CAPITAL_R;
	} else if ( currentChar == 'a') {
		return CT_SMALL_A;
	} else if ( currentChar == 'A') {
		return CT_CAPITAL_A;
	} else if ( currentChar == 'd') {
		return CT_SMALL_D;
	} else if ( currentChar == 'D') {
		return CT_CAPITAL_D;
	} else if ( currentChar == 'n') {
		return CT_SMALL_N;
	} else if ( currentChar == 'N') {
		return CT_CAPITAL_N;
	} else if ( currentChar == 't') {
		return CT_SMALL_T;
	} else if ( currentChar == 'T') {
		return CT_CAPITAL_T;
	} else if ( currentChar == 's') {
		return CT_SMALL_S;
	} else if ( currentChar == 'S') {
		return CT_CAPITAL_S;
	} else if ( currentChar == ':') {
		return CT_SIGN_COLON;
	} else if ( currentChar == '*') {
		return CT_SIGN_STAR;
	} else if ( currentChar == '=') {
		return CT_SIGN_EQUAL;
	} else if ( currentChar == '&') {
		return CT_SIGN_AND;
	} else if ( currentChar == ' ' || currentChar == '\r' ) {
		return CT_BLANK;
		//Unter Windows kommt eine CR UND LF. Unter Linux nur LF
	} else if ( currentChar == '\n' ||currentChar == '\0') {
		return CT_LINE_BREAK;
	} else if ( currentChar == '\t') {
		return CT_TAB;
	} else if ( currentChar == '+' || currentChar == '-' ||
			currentChar == '<' || currentChar == '>' ||
			currentChar == '!' || currentChar == ';' ||
			currentChar == '(' || currentChar == ')' ||
			currentChar == '{' || currentChar == '}' ||
			currentChar == '[' || currentChar == ']' ||
			currentChar == ';') {
		return CT_SIGN;
	} else {
		return CT_NOT_ALLOWED;
	}
}

void Automat::initTransitionTable() {
	int i = 0;
	// INIT
	transitionTable[i][0]  = INTEGER;
	transitionTable[i][1]  = IDENTIFIER;
	transitionTable[i][2]  = IF_SMALL_1;
	transitionTable[i][3]  = IDENTIFIER;
	transitionTable[i][4]  = WHILE_SMALL_1;
	transitionTable[i][5]  = IDENTIFIER;
	transitionTable[i][6]  = IDENTIFIER;
	transitionTable[i][7]  = ELSE_SMALL_1;
	transitionTable[i][8]  = IF_CAPITAL_1;
	transitionTable[i][9]  = IDENTIFIER;
	transitionTable[i][10] = WHILE_CAPITAL_1;
	transitionTable[i][11] = IDENTIFIER;
	transitionTable[i][12] = IDENTIFIER;
	transitionTable[i][13] = ELSE_CAPITAL_1;
	transitionTable[i][14] = READ_SMALL_1;
	transitionTable[i][15] = IDENTIFIER;
	transitionTable[i][16] = IDENTIFIER;
	transitionTable[i][17] = IDENTIFIER;
	transitionTable[i][18] = IDENTIFIER;
	transitionTable[i][19] = IDENTIFIER;
	transitionTable[i][20] = READ_CAPITAL_1;
	transitionTable[i][21] = IDENTIFIER;
	transitionTable[i][22] = IDENTIFIER;
	transitionTable[i][23] = IDENTIFIER;
	transitionTable[i][24] = IDENTIFIER;
	transitionTable[i][25] = IDENTIFIER;
	transitionTable[i][26] = SIGN;
	transitionTable[i][27] = COLON;
	transitionTable[i][28] = STAR;
	transitionTable[i][29] = EQUAL;
	transitionTable[i][30] = AND_1;
	transitionTable[i][31] = BLANK;
	transitionTable[i][32] = LINE_BREAK;
	transitionTable[i][33] = TAB;
	transitionTable[i][34] = ERROR;


	// TOKEN
	i = 1;
	transitionTable[i][0]  = INIT;
	transitionTable[i][1]  = INIT;
	transitionTable[i][2]  = INIT;
	transitionTable[i][3]  = INIT;
	transitionTable[i][4]  = INIT;
	transitionTable[i][5]  = INIT;
	transitionTable[i][6]  = INIT;
	transitionTable[i][7]  = INIT;
	transitionTable[i][8]  = INIT;
	transitionTable[i][9]  = INIT;
	transitionTable[i][10] = INIT;
	transitionTable[i][11] = INIT;
	transitionTable[i][12] = INIT;
	transitionTable[i][13] = INIT;
	transitionTable[i][14] = INIT;
	transitionTable[i][15] = INIT;
	transitionTable[i][16] = INIT;
	transitionTable[i][17] = INIT;
	transitionTable[i][18] = INIT;
	transitionTable[i][19] = INIT;
	transitionTable[i][20] = INIT;
	transitionTable[i][21] = INIT;
	transitionTable[i][22] = INIT;
	transitionTable[i][23] = INIT;
	transitionTable[i][24] = INIT;
	transitionTable[i][25] = INIT;
	transitionTable[i][26] = INIT;
	transitionTable[i][27] = INIT;
	transitionTable[i][28] = INIT;
	transitionTable[i][29] = INIT;
	transitionTable[i][30] = INIT;
	transitionTable[i][31] = INIT;
	transitionTable[i][32] = INIT;
	transitionTable[i][33] = INIT;
	transitionTable[i][34] = INIT;


	// ERROR
	i = 2;
	transitionTable[i][0]  = TOKEN;
	transitionTable[i][1]  = TOKEN;
	transitionTable[i][2]  = TOKEN;
	transitionTable[i][3]  = TOKEN;
	transitionTable[i][4]  = TOKEN;
	transitionTable[i][5]  = TOKEN;
	transitionTable[i][6]  = TOKEN;
	transitionTable[i][7]  = TOKEN;
	transitionTable[i][8]  = TOKEN;
	transitionTable[i][9]  = TOKEN;
	transitionTable[i][10] = TOKEN;
	transitionTable[i][11] = TOKEN;
	transitionTable[i][12] = TOKEN;
	transitionTable[i][13] = TOKEN;
	transitionTable[i][14] = TOKEN;
	transitionTable[i][15] = TOKEN;
	transitionTable[i][16] = TOKEN;
	transitionTable[i][17] = TOKEN;
	transitionTable[i][18] = TOKEN;
	transitionTable[i][19] = TOKEN;
	transitionTable[i][20] = TOKEN;
	transitionTable[i][21] = TOKEN;
	transitionTable[i][22] = TOKEN;
	transitionTable[i][23] = TOKEN;
	transitionTable[i][24] = TOKEN;
	transitionTable[i][25] = TOKEN;
	transitionTable[i][26] = TOKEN;
	transitionTable[i][27] = TOKEN;
	transitionTable[i][28] = TOKEN;
	transitionTable[i][29] = TOKEN;
	transitionTable[i][30] = TOKEN;
	transitionTable[i][31] = TOKEN;
	transitionTable[i][32] = TOKEN;
	transitionTable[i][33] = TOKEN;
	transitionTable[i][34] = TOKEN;

	// BLANK
	i = 3;
	transitionTable[i][0]  = INIT;
	transitionTable[i][1]  = INIT;
	transitionTable[i][2]  = INIT;
	transitionTable[i][3]  = INIT;
	transitionTable[i][4]  = INIT;
	transitionTable[i][5]  = INIT;
	transitionTable[i][6]  = INIT;
	transitionTable[i][7]  = INIT;
	transitionTable[i][8]  = INIT;
	transitionTable[i][9]  = INIT;
	transitionTable[i][10] = INIT;
	transitionTable[i][11] = INIT;
	transitionTable[i][12] = INIT;
	transitionTable[i][13] = INIT;
	transitionTable[i][14] = INIT;
	transitionTable[i][15] = INIT;
	transitionTable[i][16] = INIT;
	transitionTable[i][17] = INIT;
	transitionTable[i][18] = INIT;
	transitionTable[i][19] = INIT;
	transitionTable[i][20] = INIT;
	transitionTable[i][21] = INIT;
	transitionTable[i][22] = INIT;
	transitionTable[i][23] = INIT;
	transitionTable[i][24] = INIT;
	transitionTable[i][25] = INIT;
	transitionTable[i][26] = INIT;
	transitionTable[i][27] = INIT;
	transitionTable[i][28] = INIT;
	transitionTable[i][29] = INIT;
	transitionTable[i][30] = INIT;
	transitionTable[i][31] = INIT;
	transitionTable[i][32] = INIT;
	transitionTable[i][33] = INIT;
	transitionTable[i][34] = INIT;

	// LINE_BREAK
	i = 4;
	transitionTable[i][0]  = TOKEN;
	transitionTable[i][1]  = TOKEN;
	transitionTable[i][2]  = TOKEN;
	transitionTable[i][3]  = TOKEN;
	transitionTable[i][4]  = TOKEN;
	transitionTable[i][5]  = TOKEN;
	transitionTable[i][6]  = TOKEN;
	transitionTable[i][7]  = TOKEN;
	transitionTable[i][8]  = TOKEN;
	transitionTable[i][9]  = TOKEN;
	transitionTable[i][10] = TOKEN;
	transitionTable[i][11] = TOKEN;
	transitionTable[i][12] = TOKEN;
	transitionTable[i][13] = TOKEN;
	transitionTable[i][14] = TOKEN;
	transitionTable[i][15] = TOKEN;
	transitionTable[i][16] = TOKEN;
	transitionTable[i][17] = TOKEN;
	transitionTable[i][18] = TOKEN;
	transitionTable[i][19] = TOKEN;
	transitionTable[i][20] = TOKEN;
	transitionTable[i][21] = TOKEN;
	transitionTable[i][22] = TOKEN;
	transitionTable[i][23] = TOKEN;
	transitionTable[i][24] = TOKEN;
	transitionTable[i][25] = TOKEN;
	transitionTable[i][26] = TOKEN;
	transitionTable[i][27] = TOKEN;
	transitionTable[i][28] = TOKEN;
	transitionTable[i][29] = TOKEN;
	transitionTable[i][30] = TOKEN;
	transitionTable[i][31] = TOKEN;
	transitionTable[i][32] = TOKEN;
	transitionTable[i][33] = TOKEN;
	transitionTable[i][34] = TOKEN;

	// TAB
	i = 5;
	transitionTable[i][0]  = TOKEN;
	transitionTable[i][1]  = TOKEN;
	transitionTable[i][2]  = TOKEN;
	transitionTable[i][3]  = TOKEN;
	transitionTable[i][4]  = TOKEN;
	transitionTable[i][5]  = TOKEN;
	transitionTable[i][6]  = TOKEN;
	transitionTable[i][7]  = TOKEN;
	transitionTable[i][8]  = TOKEN;
	transitionTable[i][9]  = TOKEN;
	transitionTable[i][10] = TOKEN;
	transitionTable[i][11] = TOKEN;
	transitionTable[i][12] = TOKEN;
	transitionTable[i][13] = TOKEN;
	transitionTable[i][14] = TOKEN;
	transitionTable[i][15] = TOKEN;
	transitionTable[i][16] = TOKEN;
	transitionTable[i][17] = TOKEN;
	transitionTable[i][18] = TOKEN;
	transitionTable[i][19] = TOKEN;
	transitionTable[i][20] = TOKEN;
	transitionTable[i][21] = TOKEN;
	transitionTable[i][22] = TOKEN;
	transitionTable[i][23] = TOKEN;
	transitionTable[i][24] = TOKEN;
	transitionTable[i][25] = TOKEN;
	transitionTable[i][26] = TOKEN;
	transitionTable[i][27] = TOKEN;
	transitionTable[i][28] = TOKEN;
	transitionTable[i][29] = TOKEN;
	transitionTable[i][30] = TOKEN;
	transitionTable[i][31] = TOKEN;
	transitionTable[i][32] = TOKEN;
	transitionTable[i][33] = TOKEN;
	transitionTable[i][34] = TOKEN;

	// INTEGER
	i = 6;
	transitionTable[i][0]  = INTEGER;
	transitionTable[i][1]  = TOKEN;
	transitionTable[i][2]  = TOKEN;
	transitionTable[i][3]  = TOKEN;
	transitionTable[i][4]  = TOKEN;
	transitionTable[i][5]  = TOKEN;
	transitionTable[i][6]  = TOKEN;
	transitionTable[i][7]  = TOKEN;
	transitionTable[i][8]  = TOKEN;
	transitionTable[i][9]  = TOKEN;
	transitionTable[i][10] = TOKEN;
	transitionTable[i][11] = TOKEN;
	transitionTable[i][12] = TOKEN;
	transitionTable[i][13] = TOKEN;
	transitionTable[i][14] = TOKEN;
	transitionTable[i][15] = TOKEN;
	transitionTable[i][16] = TOKEN;
	transitionTable[i][17] = TOKEN;
	transitionTable[i][18] = TOKEN;
	transitionTable[i][19] = TOKEN;
	transitionTable[i][20] = TOKEN;
	transitionTable[i][21] = TOKEN;
	transitionTable[i][22] = TOKEN;
	transitionTable[i][23] = TOKEN;
	transitionTable[i][24] = TOKEN;
	transitionTable[i][25] = TOKEN;
	transitionTable[i][26] = TOKEN;
	transitionTable[i][27] = TOKEN;
	transitionTable[i][28] = TOKEN;
	transitionTable[i][29] = TOKEN;
	transitionTable[i][30] = TOKEN;
	transitionTable[i][31] = TOKEN;
	transitionTable[i][32] = TOKEN;
	transitionTable[i][33] = TOKEN;
	transitionTable[i][34] = TOKEN;

	// IDENTIFIER
	i = 7;
	transitionTable[i][0]  = IDENTIFIER;
	transitionTable[i][1]  = IDENTIFIER;
	transitionTable[i][2]  = IDENTIFIER;
	transitionTable[i][3]  = IDENTIFIER;
	transitionTable[i][4]  = IDENTIFIER;
	transitionTable[i][5]  = IDENTIFIER;
	transitionTable[i][6]  = IDENTIFIER;
	transitionTable[i][7]  = IDENTIFIER;
	transitionTable[i][8]  = IDENTIFIER;
	transitionTable[i][9]  = IDENTIFIER;
	transitionTable[i][10] = IDENTIFIER;
	transitionTable[i][11] = IDENTIFIER;
	transitionTable[i][12] = IDENTIFIER;
	transitionTable[i][13] = IDENTIFIER;
	transitionTable[i][14] = IDENTIFIER;
	transitionTable[i][15] = IDENTIFIER;
	transitionTable[i][16] = IDENTIFIER;
	transitionTable[i][17] = IDENTIFIER;
	transitionTable[i][18] = IDENTIFIER;
	transitionTable[i][19] = IDENTIFIER;
	transitionTable[i][20] = IDENTIFIER;
	transitionTable[i][21] = IDENTIFIER;
	transitionTable[i][22] = IDENTIFIER;
	transitionTable[i][23] = IDENTIFIER;
	transitionTable[i][24] = IDENTIFIER;
	transitionTable[i][25] = IDENTIFIER;
	transitionTable[i][26] = TOKEN;
	transitionTable[i][27] = TOKEN;
	transitionTable[i][28] = TOKEN;
	transitionTable[i][29] = TOKEN;
	transitionTable[i][30] = TOKEN;
	transitionTable[i][31] = TOKEN;
	transitionTable[i][32] = TOKEN;
	transitionTable[i][33] = TOKEN;
	transitionTable[i][34] = TOKEN;

	// IF_SMALL_1
	i = 8;
	transitionTable[i][0]  = IDENTIFIER;
	transitionTable[i][1]  = IDENTIFIER;
	transitionTable[i][2]  = IDENTIFIER;
	transitionTable[i][3]  = IF;
	transitionTable[i][4]  = IDENTIFIER;
	transitionTable[i][5]  = IDENTIFIER;
	transitionTable[i][6]  = IDENTIFIER;
	transitionTable[i][7]  = IDENTIFIER;
	transitionTable[i][8]  = IDENTIFIER;
	transitionTable[i][9]  = IDENTIFIER;
	transitionTable[i][10] = IDENTIFIER;
	transitionTable[i][11] = IDENTIFIER;
	transitionTable[i][12] = IDENTIFIER;
	transitionTable[i][13] = IDENTIFIER;
	transitionTable[i][14] = IDENTIFIER;
	transitionTable[i][15] = IDENTIFIER;
	transitionTable[i][16] = IDENTIFIER;
	transitionTable[i][17] = INT_SMALL_1;
	transitionTable[i][18] = IDENTIFIER;
	transitionTable[i][19] = IDENTIFIER;
	transitionTable[i][20] = IDENTIFIER;
	transitionTable[i][21] = IDENTIFIER;
	transitionTable[i][22] = IDENTIFIER;
	transitionTable[i][23] = IDENTIFIER;
	transitionTable[i][24] = IDENTIFIER;
	transitionTable[i][25] = IDENTIFIER;
	transitionTable[i][26] = TOKEN;
	transitionTable[i][27] = TOKEN;
	transitionTable[i][28] = TOKEN;
	transitionTable[i][29] = TOKEN;
	transitionTable[i][30] = TOKEN;
	transitionTable[i][31] = TOKEN;
	transitionTable[i][32] = TOKEN;
	transitionTable[i][33] = TOKEN;
	transitionTable[i][34] = TOKEN;

	// IF_CAPITAL_1
	i = 9;
	transitionTable[i][0]  = IDENTIFIER;
	transitionTable[i][1]  = IDENTIFIER;
	transitionTable[i][2]  = IDENTIFIER;
	transitionTable[i][3]  = IDENTIFIER;
	transitionTable[i][4]  = IDENTIFIER;
	transitionTable[i][5]  = IDENTIFIER;
	transitionTable[i][6]  = IDENTIFIER;
	transitionTable[i][7]  = IDENTIFIER;
	transitionTable[i][8]  = IDENTIFIER;
	transitionTable[i][9]  = IF;
	transitionTable[i][10] = IDENTIFIER;
	transitionTable[i][11] = IDENTIFIER;
	transitionTable[i][12] = IDENTIFIER;
	transitionTable[i][13] = IDENTIFIER;
	transitionTable[i][14] = IDENTIFIER;
	transitionTable[i][15] = IDENTIFIER;
	transitionTable[i][16] = IDENTIFIER;
	transitionTable[i][17] = IDENTIFIER;
	transitionTable[i][18] = IDENTIFIER;
	transitionTable[i][19] = IDENTIFIER;
	transitionTable[i][20] = IDENTIFIER;
	transitionTable[i][21] = IDENTIFIER;
	transitionTable[i][22] = IDENTIFIER;
	transitionTable[i][23] = INT_CAPITAL_1;
	transitionTable[i][24] = IDENTIFIER;
	transitionTable[i][25] = IDENTIFIER;
	transitionTable[i][26] = TOKEN;
	transitionTable[i][27] = TOKEN;
	transitionTable[i][28] = TOKEN;
	transitionTable[i][29] = TOKEN;
	transitionTable[i][30] = TOKEN;
	transitionTable[i][31] = TOKEN;
	transitionTable[i][32] = TOKEN;
	transitionTable[i][33] = TOKEN;
	transitionTable[i][34] = TOKEN;

	// IF
	i = 10;
	transitionTable[i][0]  = IDENTIFIER;
	transitionTable[i][1]  = IDENTIFIER;
	transitionTable[i][2]  = IDENTIFIER;
	transitionTable[i][3]  = IDENTIFIER;
	transitionTable[i][4]  = IDENTIFIER;
	transitionTable[i][5]  = IDENTIFIER;
	transitionTable[i][6]  = IDENTIFIER;
	transitionTable[i][7]  = IDENTIFIER;
	transitionTable[i][8]  = IDENTIFIER;
	transitionTable[i][9]  = IDENTIFIER;
	transitionTable[i][10] = IDENTIFIER;
	transitionTable[i][11] = IDENTIFIER;
	transitionTable[i][12] = IDENTIFIER;
	transitionTable[i][13] = IDENTIFIER;
	transitionTable[i][14] = IDENTIFIER;
	transitionTable[i][15] = IDENTIFIER;
	transitionTable[i][16] = IDENTIFIER;
	transitionTable[i][17] = IDENTIFIER;
	transitionTable[i][18] = IDENTIFIER;
	transitionTable[i][19] = IDENTIFIER;
	transitionTable[i][20] = IDENTIFIER;
	transitionTable[i][21] = IDENTIFIER;
	transitionTable[i][22] = IDENTIFIER;
	transitionTable[i][23] = IDENTIFIER;
	transitionTable[i][24] = IDENTIFIER;
	transitionTable[i][25] = IDENTIFIER;
	transitionTable[i][26] = TOKEN;
	transitionTable[i][27] = TOKEN;
	transitionTable[i][28] = TOKEN;
	transitionTable[i][29] = TOKEN;
	transitionTable[i][30] = TOKEN;
	transitionTable[i][31] = TOKEN;
	transitionTable[i][32] = TOKEN;
	transitionTable[i][33] = TOKEN;
	transitionTable[i][34] = TOKEN;

	// WHILE_SMALL_1
	i = 11;
	transitionTable[i][0]  = IDENTIFIER;
	transitionTable[i][1]  = IDENTIFIER;
	transitionTable[i][2]  = IDENTIFIER;
	transitionTable[i][3]  = IDENTIFIER;
	transitionTable[i][4]  = IDENTIFIER;
	transitionTable[i][5]  = WHILE_SMALL_2;
	transitionTable[i][6]  = IDENTIFIER;
	transitionTable[i][7]  = IDENTIFIER;
	transitionTable[i][8]  = IDENTIFIER;
	transitionTable[i][9]  = IDENTIFIER;
	transitionTable[i][10] = IDENTIFIER;
	transitionTable[i][11] = IDENTIFIER;
	transitionTable[i][12] = IDENTIFIER;
	transitionTable[i][13] = IDENTIFIER;
	transitionTable[i][14] = WRITE_SMALL_1;
	transitionTable[i][15] = IDENTIFIER;
	transitionTable[i][16] = IDENTIFIER;
	transitionTable[i][17] = IDENTIFIER;
	transitionTable[i][18] = IDENTIFIER;
	transitionTable[i][19] = IDENTIFIER;
	transitionTable[i][20] = IDENTIFIER;
	transitionTable[i][21] = IDENTIFIER;
	transitionTable[i][22] = IDENTIFIER;
	transitionTable[i][23] = IDENTIFIER;
	transitionTable[i][24] = IDENTIFIER;
	transitionTable[i][25] = IDENTIFIER;
	transitionTable[i][26] = TOKEN;
	transitionTable[i][27] = TOKEN;
	transitionTable[i][28] = TOKEN;
	transitionTable[i][29] = TOKEN;
	transitionTable[i][30] = TOKEN;
	transitionTable[i][31] = TOKEN;
	transitionTable[i][32] = TOKEN;
	transitionTable[i][33] = TOKEN;
	transitionTable[i][34] = TOKEN;

	// WHILE_SMALL_2
	i = 12;
	transitionTable[i][0]  = IDENTIFIER;
	transitionTable[i][1]  = IDENTIFIER;
	transitionTable[i][2]  = WHILE_SMALL_3;
	transitionTable[i][3]  = IDENTIFIER;
	transitionTable[i][4]  = IDENTIFIER;
	transitionTable[i][5]  = IDENTIFIER;
	transitionTable[i][6]  = IDENTIFIER;
	transitionTable[i][7]  = IDENTIFIER;
	transitionTable[i][8]  = IDENTIFIER;
	transitionTable[i][9]  = IDENTIFIER;
	transitionTable[i][10] = IDENTIFIER;
	transitionTable[i][11] = IDENTIFIER;
	transitionTable[i][12] = IDENTIFIER;
	transitionTable[i][13] = IDENTIFIER;
	transitionTable[i][14] = IDENTIFIER;
	transitionTable[i][15] = IDENTIFIER;
	transitionTable[i][16] = IDENTIFIER;
	transitionTable[i][17] = IDENTIFIER;
	transitionTable[i][18] = IDENTIFIER;
	transitionTable[i][19] = IDENTIFIER;
	transitionTable[i][20] = IDENTIFIER;
	transitionTable[i][21] = IDENTIFIER;
	transitionTable[i][22] = IDENTIFIER;
	transitionTable[i][23] = IDENTIFIER;
	transitionTable[i][24] = IDENTIFIER;
	transitionTable[i][25] = IDENTIFIER;
	transitionTable[i][26] = TOKEN;
	transitionTable[i][27] = TOKEN;
	transitionTable[i][28] = TOKEN;
	transitionTable[i][29] = TOKEN;
	transitionTable[i][30] = TOKEN;
	transitionTable[i][31] = TOKEN;
	transitionTable[i][32] = TOKEN;
	transitionTable[i][33] = TOKEN;
	transitionTable[i][34] = TOKEN;

	// WHILE_SMALL_3
	i = 13;
	transitionTable[i][0]  = IDENTIFIER;
	transitionTable[i][1]  = IDENTIFIER;
	transitionTable[i][2]  = IDENTIFIER;
	transitionTable[i][3]  = IDENTIFIER;
	transitionTable[i][4]  = IDENTIFIER;
	transitionTable[i][5]  = IDENTIFIER;
	transitionTable[i][6]  = WHILE_SMALL_4;
	transitionTable[i][7]  = IDENTIFIER;
	transitionTable[i][8]  = IDENTIFIER;
	transitionTable[i][9]  = IDENTIFIER;
	transitionTable[i][10] = IDENTIFIER;
	transitionTable[i][11] = IDENTIFIER;
	transitionTable[i][12] = IDENTIFIER;
	transitionTable[i][13] = IDENTIFIER;
	transitionTable[i][14] = IDENTIFIER;
	transitionTable[i][15] = IDENTIFIER;
	transitionTable[i][16] = IDENTIFIER;
	transitionTable[i][17] = IDENTIFIER;
	transitionTable[i][18] = IDENTIFIER;
	transitionTable[i][19] = IDENTIFIER;
	transitionTable[i][20] = IDENTIFIER;
	transitionTable[i][21] = IDENTIFIER;
	transitionTable[i][22] = IDENTIFIER;
	transitionTable[i][23] = IDENTIFIER;
	transitionTable[i][24] = IDENTIFIER;
	transitionTable[i][25] = IDENTIFIER;
	transitionTable[i][26] = TOKEN;
	transitionTable[i][27] = TOKEN;
	transitionTable[i][28] = TOKEN;
	transitionTable[i][29] = TOKEN;
	transitionTable[i][30] = TOKEN;
	transitionTable[i][31] = TOKEN;
	transitionTable[i][32] = TOKEN;
	transitionTable[i][33] = TOKEN;
	transitionTable[i][34] = TOKEN;

	// WHILE_SMALL_4
	i = 14;
	transitionTable[i][0]  = IDENTIFIER;
	transitionTable[i][1]  = IDENTIFIER;
	transitionTable[i][2]  = IDENTIFIER;
	transitionTable[i][3]  = IDENTIFIER;
	transitionTable[i][4]  = IDENTIFIER;
	transitionTable[i][5]  = IDENTIFIER;
	transitionTable[i][6]  = IDENTIFIER;
	transitionTable[i][7]  = WHILE;
	transitionTable[i][8]  = IDENTIFIER;
	transitionTable[i][9]  = IDENTIFIER;
	transitionTable[i][10] = IDENTIFIER;
	transitionTable[i][11] = IDENTIFIER;
	transitionTable[i][12] = IDENTIFIER;
	transitionTable[i][13] = IDENTIFIER;
	transitionTable[i][14] = IDENTIFIER;
	transitionTable[i][15] = IDENTIFIER;
	transitionTable[i][16] = IDENTIFIER;
	transitionTable[i][17] = IDENTIFIER;
	transitionTable[i][18] = IDENTIFIER;
	transitionTable[i][19] = IDENTIFIER;
	transitionTable[i][20] = IDENTIFIER;
	transitionTable[i][21] = IDENTIFIER;
	transitionTable[i][22] = IDENTIFIER;
	transitionTable[i][23] = IDENTIFIER;
	transitionTable[i][24] = IDENTIFIER;
	transitionTable[i][25] = IDENTIFIER;
	transitionTable[i][26] = TOKEN;
	transitionTable[i][27] = TOKEN;
	transitionTable[i][28] = TOKEN;
	transitionTable[i][29] = TOKEN;
	transitionTable[i][30] = TOKEN;
	transitionTable[i][31] = TOKEN;
	transitionTable[i][32] = TOKEN;
	transitionTable[i][33] = TOKEN;
	transitionTable[i][34] = TOKEN;

	// WHILE_CAPITAL_1
	i = 15;
	transitionTable[i][0]  = IDENTIFIER;
	transitionTable[i][1]  = IDENTIFIER;
	transitionTable[i][2]  = IDENTIFIER;
	transitionTable[i][3]  = IDENTIFIER;
	transitionTable[i][4]  = IDENTIFIER;
	transitionTable[i][5]  = IDENTIFIER;
	transitionTable[i][6]  = IDENTIFIER;
	transitionTable[i][7]  = IDENTIFIER;
	transitionTable[i][8]  = IDENTIFIER;
	transitionTable[i][9]  = IDENTIFIER;
	transitionTable[i][10] = IDENTIFIER;
	transitionTable[i][11] = WHILE_CAPITAL_2;
	transitionTable[i][12] = IDENTIFIER;
	transitionTable[i][13] = IDENTIFIER;
	transitionTable[i][14] = IDENTIFIER;
	transitionTable[i][15] = IDENTIFIER;
	transitionTable[i][16] = IDENTIFIER;
	transitionTable[i][17] = IDENTIFIER;
	transitionTable[i][18] = IDENTIFIER;
	transitionTable[i][19] = IDENTIFIER;
	transitionTable[i][20] = WRITE_CAPITAL_1;
	transitionTable[i][21] = IDENTIFIER;
	transitionTable[i][22] = IDENTIFIER;
	transitionTable[i][23] = IDENTIFIER;
	transitionTable[i][24] = IDENTIFIER;
	transitionTable[i][25] = IDENTIFIER;
	transitionTable[i][26] = TOKEN;
	transitionTable[i][27] = TOKEN;
	transitionTable[i][28] = TOKEN;
	transitionTable[i][29] = TOKEN;
	transitionTable[i][30] = TOKEN;
	transitionTable[i][31] = TOKEN;
	transitionTable[i][32] = TOKEN;
	transitionTable[i][33] = TOKEN;
	transitionTable[i][34] = TOKEN;

	// WHILE_CAPITAL_2
	i = 16;
	transitionTable[i][0]  = IDENTIFIER;
	transitionTable[i][1]  = IDENTIFIER;
	transitionTable[i][2]  = IDENTIFIER;
	transitionTable[i][3]  = IDENTIFIER;
	transitionTable[i][4]  = IDENTIFIER;
	transitionTable[i][5]  = IDENTIFIER;
	transitionTable[i][6]  = IDENTIFIER;
	transitionTable[i][7]  = IDENTIFIER;
	transitionTable[i][8]  = WHILE_CAPITAL_3;
	transitionTable[i][9]  = IDENTIFIER;
	transitionTable[i][10] = IDENTIFIER;
	transitionTable[i][11] = IDENTIFIER;
	transitionTable[i][12] = IDENTIFIER;
	transitionTable[i][13] = IDENTIFIER;
	transitionTable[i][14] = IDENTIFIER;
	transitionTable[i][15] = IDENTIFIER;
	transitionTable[i][16] = IDENTIFIER;
	transitionTable[i][17] = IDENTIFIER;
	transitionTable[i][18] = IDENTIFIER;
	transitionTable[i][19] = IDENTIFIER;
	transitionTable[i][20] = IDENTIFIER;
	transitionTable[i][21] = IDENTIFIER;
	transitionTable[i][22] = IDENTIFIER;
	transitionTable[i][23] = IDENTIFIER;
	transitionTable[i][24] = IDENTIFIER;
	transitionTable[i][25] = IDENTIFIER;
	transitionTable[i][26] = TOKEN;
	transitionTable[i][27] = TOKEN;
	transitionTable[i][28] = TOKEN;
	transitionTable[i][29] = TOKEN;
	transitionTable[i][30] = TOKEN;
	transitionTable[i][31] = TOKEN;
	transitionTable[i][32] = TOKEN;
	transitionTable[i][33] = TOKEN;
	transitionTable[i][34] = TOKEN;

	// WHILE_CAPITAL_3
	i = 17;
	transitionTable[i][0]  = IDENTIFIER;
	transitionTable[i][1]  = IDENTIFIER;
	transitionTable[i][2]  = IDENTIFIER;
	transitionTable[i][3]  = IDENTIFIER;
	transitionTable[i][4]  = IDENTIFIER;
	transitionTable[i][5]  = IDENTIFIER;
	transitionTable[i][6]  = IDENTIFIER;
	transitionTable[i][7]  = IDENTIFIER;
	transitionTable[i][8]  = IDENTIFIER;
	transitionTable[i][9]  = IDENTIFIER;
	transitionTable[i][10] = IDENTIFIER;
	transitionTable[i][11] = IDENTIFIER;
	transitionTable[i][12] = WHILE_CAPITAL_4;
	transitionTable[i][13] = IDENTIFIER;
	transitionTable[i][14] = IDENTIFIER;
	transitionTable[i][15] = IDENTIFIER;
	transitionTable[i][16] = IDENTIFIER;
	transitionTable[i][17] = IDENTIFIER;
	transitionTable[i][18] = IDENTIFIER;
	transitionTable[i][19] = IDENTIFIER;
	transitionTable[i][20] = IDENTIFIER;
	transitionTable[i][21] = IDENTIFIER;
	transitionTable[i][22] = IDENTIFIER;
	transitionTable[i][23] = IDENTIFIER;
	transitionTable[i][24] = IDENTIFIER;
	transitionTable[i][25] = IDENTIFIER;
	transitionTable[i][26] = TOKEN;
	transitionTable[i][27] = TOKEN;
	transitionTable[i][28] = TOKEN;
	transitionTable[i][29] = TOKEN;
	transitionTable[i][30] = TOKEN;
	transitionTable[i][31] = TOKEN;
	transitionTable[i][32] = TOKEN;
	transitionTable[i][33] = TOKEN;
	transitionTable[i][34] = TOKEN;

	// WHILE_CAPITAL_4
	i = 18;
	transitionTable[i][0]  = IDENTIFIER;
	transitionTable[i][1]  = IDENTIFIER;
	transitionTable[i][2]  = IDENTIFIER;
	transitionTable[i][3]  = IDENTIFIER;
	transitionTable[i][4]  = IDENTIFIER;
	transitionTable[i][5]  = IDENTIFIER;
	transitionTable[i][6]  = IDENTIFIER;
	transitionTable[i][7]  = IDENTIFIER;
	transitionTable[i][8]  = IDENTIFIER;
	transitionTable[i][9]  = IDENTIFIER;
	transitionTable[i][10] = IDENTIFIER;
	transitionTable[i][11] = IDENTIFIER;
	transitionTable[i][12] = IDENTIFIER;
	transitionTable[i][13] = WHILE;
	transitionTable[i][14] = IDENTIFIER;
	transitionTable[i][15] = IDENTIFIER;
	transitionTable[i][16] = IDENTIFIER;
	transitionTable[i][17] = IDENTIFIER;
	transitionTable[i][18] = IDENTIFIER;
	transitionTable[i][19] = IDENTIFIER;
	transitionTable[i][20] = IDENTIFIER;
	transitionTable[i][21] = IDENTIFIER;
	transitionTable[i][22] = IDENTIFIER;
	transitionTable[i][23] = IDENTIFIER;
	transitionTable[i][24] = IDENTIFIER;
	transitionTable[i][25] = IDENTIFIER;
	transitionTable[i][26] = TOKEN;
	transitionTable[i][27] = TOKEN;
	transitionTable[i][28] = TOKEN;
	transitionTable[i][29] = TOKEN;
	transitionTable[i][30] = TOKEN;
	transitionTable[i][31] = TOKEN;
	transitionTable[i][32] = TOKEN;
	transitionTable[i][33] = TOKEN;
	transitionTable[i][34] = TOKEN;

	// WHILE
	i = 19;
	transitionTable[i][0]  = IDENTIFIER;
	transitionTable[i][1]  = IDENTIFIER;
	transitionTable[i][2]  = IDENTIFIER;
	transitionTable[i][3]  = IDENTIFIER;
	transitionTable[i][4]  = IDENTIFIER;
	transitionTable[i][5]  = IDENTIFIER;
	transitionTable[i][6]  = IDENTIFIER;
	transitionTable[i][7]  = IDENTIFIER;
	transitionTable[i][8]  = IDENTIFIER;
	transitionTable[i][9]  = IDENTIFIER;
	transitionTable[i][10] = IDENTIFIER;
	transitionTable[i][11] = IDENTIFIER;
	transitionTable[i][12] = IDENTIFIER;
	transitionTable[i][13] = IDENTIFIER;
	transitionTable[i][14] = IDENTIFIER;
	transitionTable[i][15] = IDENTIFIER;
	transitionTable[i][16] = IDENTIFIER;
	transitionTable[i][17] = IDENTIFIER;
	transitionTable[i][18] = IDENTIFIER;
	transitionTable[i][19] = IDENTIFIER;
	transitionTable[i][20] = IDENTIFIER;
	transitionTable[i][21] = IDENTIFIER;
	transitionTable[i][22] = IDENTIFIER;
	transitionTable[i][23] = IDENTIFIER;
	transitionTable[i][24] = IDENTIFIER;
	transitionTable[i][25] = IDENTIFIER;
	transitionTable[i][26] = TOKEN;
	transitionTable[i][27] = TOKEN;
	transitionTable[i][28] = TOKEN;
	transitionTable[i][29] = TOKEN;
	transitionTable[i][30] = TOKEN;
	transitionTable[i][31] = TOKEN;
	transitionTable[i][32] = TOKEN;
	transitionTable[i][33] = TOKEN;
	transitionTable[i][34] = TOKEN;

	// READ_SMALL_1
	i = 20;
	transitionTable[i][0]  = IDENTIFIER;
	transitionTable[i][1]  = IDENTIFIER;
	transitionTable[i][2]  = IDENTIFIER;
	transitionTable[i][3]  = IDENTIFIER;
	transitionTable[i][4]  = IDENTIFIER;
	transitionTable[i][5]  = IDENTIFIER;
	transitionTable[i][6]  = IDENTIFIER;
	transitionTable[i][7]  = READ_SMALL_2;
	transitionTable[i][8]  = IDENTIFIER;
	transitionTable[i][9]  = IDENTIFIER;
	transitionTable[i][10] = IDENTIFIER;
	transitionTable[i][11] = IDENTIFIER;
	transitionTable[i][12] = IDENTIFIER;
	transitionTable[i][13] = IDENTIFIER;
	transitionTable[i][14] = IDENTIFIER;
	transitionTable[i][15] = IDENTIFIER;
	transitionTable[i][16] = IDENTIFIER;
	transitionTable[i][17] = IDENTIFIER;
	transitionTable[i][18] = IDENTIFIER;
	transitionTable[i][19] = IDENTIFIER;
	transitionTable[i][20] = IDENTIFIER;
	transitionTable[i][21] = IDENTIFIER;
	transitionTable[i][22] = IDENTIFIER;
	transitionTable[i][23] = IDENTIFIER;
	transitionTable[i][24] = IDENTIFIER;
	transitionTable[i][25] = IDENTIFIER;
	transitionTable[i][26] = TOKEN;
	transitionTable[i][27] = TOKEN;
	transitionTable[i][28] = TOKEN;
	transitionTable[i][29] = TOKEN;
	transitionTable[i][30] = TOKEN;
	transitionTable[i][31] = TOKEN;
	transitionTable[i][32] = TOKEN;
	transitionTable[i][33] = TOKEN;
	transitionTable[i][34] = TOKEN;


	// READ_SMALL_2
	i = 21;
	transitionTable[i][0]  = IDENTIFIER;
	transitionTable[i][1]  = IDENTIFIER;
	transitionTable[i][2]  = IDENTIFIER;
	transitionTable[i][3]  = IDENTIFIER;
	transitionTable[i][4]  = IDENTIFIER;
	transitionTable[i][5]  = IDENTIFIER;
	transitionTable[i][6]  = IDENTIFIER;
	transitionTable[i][7]  = IDENTIFIER;
	transitionTable[i][8]  = IDENTIFIER;
	transitionTable[i][9]  = IDENTIFIER;
	transitionTable[i][10] = IDENTIFIER;
	transitionTable[i][11] = IDENTIFIER;
	transitionTable[i][12] = IDENTIFIER;
	transitionTable[i][13] = IDENTIFIER;
	transitionTable[i][14] = IDENTIFIER;
	transitionTable[i][15] = READ_SMALL_3;
	transitionTable[i][16] = IDENTIFIER;
	transitionTable[i][17] = IDENTIFIER;
	transitionTable[i][18] = IDENTIFIER;
	transitionTable[i][19] = IDENTIFIER;
	transitionTable[i][20] = IDENTIFIER;
	transitionTable[i][21] = IDENTIFIER;
	transitionTable[i][22] = IDENTIFIER;
	transitionTable[i][23] = IDENTIFIER;
	transitionTable[i][24] = IDENTIFIER;
	transitionTable[i][25] = IDENTIFIER;
	transitionTable[i][26] = TOKEN;
	transitionTable[i][27] = TOKEN;
	transitionTable[i][28] = TOKEN;
	transitionTable[i][29] = TOKEN;
	transitionTable[i][30] = TOKEN;
	transitionTable[i][31] = TOKEN;
	transitionTable[i][32] = TOKEN;
	transitionTable[i][33] = TOKEN;
	transitionTable[i][34] = TOKEN;

	// READ_SMALL_3
	i = 22;
	transitionTable[i][0]  = IDENTIFIER;
	transitionTable[i][1]  = IDENTIFIER;
	transitionTable[i][2]  = IDENTIFIER;
	transitionTable[i][3]  = IDENTIFIER;
	transitionTable[i][4]  = IDENTIFIER;
	transitionTable[i][5]  = IDENTIFIER;
	transitionTable[i][6]  = IDENTIFIER;
	transitionTable[i][7]  = IDENTIFIER;
	transitionTable[i][8]  = IDENTIFIER;
	transitionTable[i][9]  = IDENTIFIER;
	transitionTable[i][10] = IDENTIFIER;
	transitionTable[i][11] = IDENTIFIER;
	transitionTable[i][12] = IDENTIFIER;
	transitionTable[i][13] = IDENTIFIER;
	transitionTable[i][14] = IDENTIFIER;
	transitionTable[i][15] = IDENTIFIER;
	transitionTable[i][16] = READ;
	transitionTable[i][17] = IDENTIFIER;
	transitionTable[i][18] = IDENTIFIER;
	transitionTable[i][19] = IDENTIFIER;
	transitionTable[i][20] = IDENTIFIER;
	transitionTable[i][21] = IDENTIFIER;
	transitionTable[i][22] = IDENTIFIER;
	transitionTable[i][23] = IDENTIFIER;
	transitionTable[i][24] = IDENTIFIER;
	transitionTable[i][25] = IDENTIFIER;
	transitionTable[i][26] = TOKEN;
	transitionTable[i][27] = TOKEN;
	transitionTable[i][28] = TOKEN;
	transitionTable[i][29] = TOKEN;
	transitionTable[i][30] = TOKEN;
	transitionTable[i][31] = TOKEN;
	transitionTable[i][32] = TOKEN;
	transitionTable[i][33] = TOKEN;
	transitionTable[i][34] = TOKEN;

	// READ_CAPITAL_1
	i = 23;
	transitionTable[i][0]  = IDENTIFIER;
	transitionTable[i][1]  = IDENTIFIER;
	transitionTable[i][2]  = IDENTIFIER;
	transitionTable[i][3]  = IDENTIFIER;
	transitionTable[i][4]  = IDENTIFIER;
	transitionTable[i][5]  = IDENTIFIER;
	transitionTable[i][6]  = IDENTIFIER;
	transitionTable[i][7]  = IDENTIFIER;
	transitionTable[i][8]  = IDENTIFIER;
	transitionTable[i][9]  = IDENTIFIER;
	transitionTable[i][10] = IDENTIFIER;
	transitionTable[i][11] = IDENTIFIER;
	transitionTable[i][12] = IDENTIFIER;
	transitionTable[i][13] = READ_CAPITAL_2;
	transitionTable[i][14] = IDENTIFIER;
	transitionTable[i][15] = IDENTIFIER;
	transitionTable[i][16] = IDENTIFIER;
	transitionTable[i][17] = IDENTIFIER;
	transitionTable[i][18] = IDENTIFIER;
	transitionTable[i][19] = IDENTIFIER;
	transitionTable[i][20] = IDENTIFIER;
	transitionTable[i][21] = IDENTIFIER;
	transitionTable[i][22] = IDENTIFIER;
	transitionTable[i][23] = IDENTIFIER;
	transitionTable[i][24] = IDENTIFIER;
	transitionTable[i][25] = IDENTIFIER;
	transitionTable[i][26] = TOKEN;
	transitionTable[i][27] = TOKEN;
	transitionTable[i][28] = TOKEN;
	transitionTable[i][29] = TOKEN;
	transitionTable[i][30] = TOKEN;
	transitionTable[i][31] = TOKEN;
	transitionTable[i][32] = TOKEN;
	transitionTable[i][33] = TOKEN;
	transitionTable[i][34] = TOKEN;

	// READ_CAPITAL_2
	i = 24;
	transitionTable[i][0]  = IDENTIFIER;
	transitionTable[i][1]  = IDENTIFIER;
	transitionTable[i][2]  = IDENTIFIER;
	transitionTable[i][3]  = IDENTIFIER;
	transitionTable[i][4]  = IDENTIFIER;
	transitionTable[i][5]  = IDENTIFIER;
	transitionTable[i][6]  = IDENTIFIER;
	transitionTable[i][7]  = IDENTIFIER;
	transitionTable[i][8]  = IDENTIFIER;
	transitionTable[i][9]  = IDENTIFIER;
	transitionTable[i][10] = IDENTIFIER;
	transitionTable[i][11] = IDENTIFIER;
	transitionTable[i][12] = IDENTIFIER;
	transitionTable[i][13] = IDENTIFIER;
	transitionTable[i][14] = IDENTIFIER;
	transitionTable[i][15] = IDENTIFIER;
	transitionTable[i][16] = IDENTIFIER;
	transitionTable[i][17] = IDENTIFIER;
	transitionTable[i][18] = IDENTIFIER;
	transitionTable[i][19] = IDENTIFIER;
	transitionTable[i][20] = IDENTIFIER;
	transitionTable[i][21] = READ_CAPITAL_3;
	transitionTable[i][22] = IDENTIFIER;
	transitionTable[i][23] = IDENTIFIER;
	transitionTable[i][24] = IDENTIFIER;
	transitionTable[i][25] = IDENTIFIER;
	transitionTable[i][26] = TOKEN;
	transitionTable[i][27] = TOKEN;
	transitionTable[i][28] = TOKEN;
	transitionTable[i][29] = TOKEN;
	transitionTable[i][30] = TOKEN;
	transitionTable[i][31] = TOKEN;
	transitionTable[i][32] = TOKEN;
	transitionTable[i][33] = TOKEN;
	transitionTable[i][34] = TOKEN;

	// READ_CAPITAL_3
	i = 25;
	transitionTable[i][0]  = IDENTIFIER;
	transitionTable[i][1]  = IDENTIFIER;
	transitionTable[i][2]  = IDENTIFIER;
	transitionTable[i][3]  = IDENTIFIER;
	transitionTable[i][4]  = IDENTIFIER;
	transitionTable[i][5]  = IDENTIFIER;
	transitionTable[i][6]  = IDENTIFIER;
	transitionTable[i][7]  = IDENTIFIER;
	transitionTable[i][8]  = IDENTIFIER;
	transitionTable[i][9]  = IDENTIFIER;
	transitionTable[i][10] = IDENTIFIER;
	transitionTable[i][11] = IDENTIFIER;
	transitionTable[i][12] = IDENTIFIER;
	transitionTable[i][13] = IDENTIFIER;
	transitionTable[i][14] = IDENTIFIER;
	transitionTable[i][15] = IDENTIFIER;
	transitionTable[i][16] = IDENTIFIER;
	transitionTable[i][17] = IDENTIFIER;
	transitionTable[i][18] = IDENTIFIER;
	transitionTable[i][19] = IDENTIFIER;
	transitionTable[i][20] = IDENTIFIER;
	transitionTable[i][21] = IDENTIFIER;
	transitionTable[i][22] = READ;
	transitionTable[i][23] = IDENTIFIER;
	transitionTable[i][24] = IDENTIFIER;
	transitionTable[i][25] = IDENTIFIER;
	transitionTable[i][26] = TOKEN;
	transitionTable[i][27] = TOKEN;
	transitionTable[i][28] = TOKEN;
	transitionTable[i][29] = TOKEN;
	transitionTable[i][30] = TOKEN;
	transitionTable[i][31] = TOKEN;
	transitionTable[i][32] = TOKEN;
	transitionTable[i][33] = TOKEN;
	transitionTable[i][34] = TOKEN;

	// READ
	i = 26;
	transitionTable[i][0]  = IDENTIFIER;
	transitionTable[i][1]  = IDENTIFIER;
	transitionTable[i][2]  = IDENTIFIER;
	transitionTable[i][3]  = IDENTIFIER;
	transitionTable[i][4]  = IDENTIFIER;
	transitionTable[i][5]  = IDENTIFIER;
	transitionTable[i][6]  = IDENTIFIER;
	transitionTable[i][7]  = IDENTIFIER;
	transitionTable[i][8]  = IDENTIFIER;
	transitionTable[i][9]  = IDENTIFIER;
	transitionTable[i][10] = IDENTIFIER;
	transitionTable[i][11] = IDENTIFIER;
	transitionTable[i][12] = IDENTIFIER;
	transitionTable[i][13] = IDENTIFIER;
	transitionTable[i][14] = IDENTIFIER;
	transitionTable[i][15] = IDENTIFIER;
	transitionTable[i][16] = IDENTIFIER;
	transitionTable[i][17] = IDENTIFIER;
	transitionTable[i][18] = IDENTIFIER;
	transitionTable[i][19] = IDENTIFIER;
	transitionTable[i][20] = IDENTIFIER;
	transitionTable[i][21] = IDENTIFIER;
	transitionTable[i][22] = IDENTIFIER;
	transitionTable[i][23] = IDENTIFIER;
	transitionTable[i][24] = IDENTIFIER;
	transitionTable[i][25] = IDENTIFIER;
	transitionTable[i][26] = TOKEN;
	transitionTable[i][27] = TOKEN;
	transitionTable[i][28] = TOKEN;
	transitionTable[i][29] = TOKEN;
	transitionTable[i][30] = TOKEN;
	transitionTable[i][31] = TOKEN;
	transitionTable[i][32] = TOKEN;
	transitionTable[i][33] = TOKEN;
	transitionTable[i][34] = TOKEN;

	// INT_SMALL_1
	i = 27;
	transitionTable[i][0]  = IDENTIFIER;
	transitionTable[i][1]  = IDENTIFIER;
	transitionTable[i][2]  = IDENTIFIER;
	transitionTable[i][3]  = IDENTIFIER;
	transitionTable[i][4]  = IDENTIFIER;
	transitionTable[i][5]  = IDENTIFIER;
	transitionTable[i][6]  = IDENTIFIER;
	transitionTable[i][7]  = IDENTIFIER;
	transitionTable[i][8]  = IDENTIFIER;
	transitionTable[i][9]  = IDENTIFIER;
	transitionTable[i][10] = IDENTIFIER;
	transitionTable[i][11] = IDENTIFIER;
	transitionTable[i][12] = IDENTIFIER;
	transitionTable[i][13] = IDENTIFIER;
	transitionTable[i][14] = IDENTIFIER;
	transitionTable[i][15] = IDENTIFIER;
	transitionTable[i][16] = IDENTIFIER;
	transitionTable[i][17] = IDENTIFIER;
	transitionTable[i][18] = INT;
	transitionTable[i][19] = IDENTIFIER;
	transitionTable[i][20] = IDENTIFIER;
	transitionTable[i][21] = IDENTIFIER;
	transitionTable[i][22] = IDENTIFIER;
	transitionTable[i][23] = IDENTIFIER;
	transitionTable[i][24] = IDENTIFIER;
	transitionTable[i][25] = IDENTIFIER;
	transitionTable[i][26] = TOKEN;
	transitionTable[i][27] = TOKEN;
	transitionTable[i][28] = TOKEN;
	transitionTable[i][29] = TOKEN;
	transitionTable[i][30] = TOKEN;
	transitionTable[i][31] = TOKEN;
	transitionTable[i][32] = TOKEN;
	transitionTable[i][33] = TOKEN;
	transitionTable[i][34] = TOKEN;

	// INT_CAPITAL_1
	i = 28;
	transitionTable[i][0]  = IDENTIFIER;
	transitionTable[i][1]  = IDENTIFIER;
	transitionTable[i][2]  = IDENTIFIER;
	transitionTable[i][3]  = IDENTIFIER;
	transitionTable[i][4]  = IDENTIFIER;
	transitionTable[i][5]  = IDENTIFIER;
	transitionTable[i][6]  = IDENTIFIER;
	transitionTable[i][7]  = IDENTIFIER;
	transitionTable[i][8]  = IDENTIFIER;
	transitionTable[i][9]  = IDENTIFIER;
	transitionTable[i][10] = IDENTIFIER;
	transitionTable[i][11] = IDENTIFIER;
	transitionTable[i][12] = IDENTIFIER;
	transitionTable[i][13] = IDENTIFIER;
	transitionTable[i][14] = IDENTIFIER;
	transitionTable[i][15] = IDENTIFIER;
	transitionTable[i][16] = IDENTIFIER;
	transitionTable[i][17] = IDENTIFIER;
	transitionTable[i][18] = IDENTIFIER;
	transitionTable[i][19] = IDENTIFIER;
	transitionTable[i][20] = IDENTIFIER;
	transitionTable[i][21] = IDENTIFIER;
	transitionTable[i][22] = IDENTIFIER;
	transitionTable[i][23] = IDENTIFIER;
	transitionTable[i][24] = INT;
	transitionTable[i][25] = IDENTIFIER;
	transitionTable[i][26] = TOKEN;
	transitionTable[i][27] = TOKEN;
	transitionTable[i][28] = TOKEN;
	transitionTable[i][29] = TOKEN;
	transitionTable[i][30] = TOKEN;
	transitionTable[i][31] = TOKEN;
	transitionTable[i][32] = TOKEN;
	transitionTable[i][33] = TOKEN;
	transitionTable[i][34] = TOKEN;

	// INT
	i = 29;
	transitionTable[i][0]  = IDENTIFIER;
	transitionTable[i][1]  = IDENTIFIER;
	transitionTable[i][2]  = IDENTIFIER;
	transitionTable[i][3]  = IDENTIFIER;
	transitionTable[i][4]  = IDENTIFIER;
	transitionTable[i][5]  = IDENTIFIER;
	transitionTable[i][6]  = IDENTIFIER;
	transitionTable[i][7]  = IDENTIFIER;
	transitionTable[i][8]  = IDENTIFIER;
	transitionTable[i][9]  = IDENTIFIER;
	transitionTable[i][10] = IDENTIFIER;
	transitionTable[i][11] = IDENTIFIER;
	transitionTable[i][12] = IDENTIFIER;
	transitionTable[i][13] = IDENTIFIER;
	transitionTable[i][14] = IDENTIFIER;
	transitionTable[i][15] = IDENTIFIER;
	transitionTable[i][16] = IDENTIFIER;
	transitionTable[i][17] = IDENTIFIER;
	transitionTable[i][18] = IDENTIFIER;
	transitionTable[i][19] = IDENTIFIER;
	transitionTable[i][20] = IDENTIFIER;
	transitionTable[i][21] = IDENTIFIER;
	transitionTable[i][22] = IDENTIFIER;
	transitionTable[i][23] = IDENTIFIER;
	transitionTable[i][24] = IDENTIFIER;
	transitionTable[i][25] = IDENTIFIER;
	transitionTable[i][26] = TOKEN;
	transitionTable[i][27] = TOKEN;
	transitionTable[i][28] = TOKEN;
	transitionTable[i][29] = TOKEN;
	transitionTable[i][30] = TOKEN;
	transitionTable[i][31] = TOKEN;
	transitionTable[i][32] = TOKEN;
	transitionTable[i][33] = TOKEN;
	transitionTable[i][34] = TOKEN;

	// WRITE_SMALL_1
	i = 30;
	transitionTable[i][0]  = IDENTIFIER;
	transitionTable[i][1]  = IDENTIFIER;
	transitionTable[i][2]  = WRITE_SMALL_2;
	transitionTable[i][3]  = IDENTIFIER;
	transitionTable[i][4]  = IDENTIFIER;
	transitionTable[i][5]  = IDENTIFIER;
	transitionTable[i][6]  = IDENTIFIER;
	transitionTable[i][7]  = IDENTIFIER;
	transitionTable[i][8]  = IDENTIFIER;
	transitionTable[i][9]  = IDENTIFIER;
	transitionTable[i][10] = IDENTIFIER;
	transitionTable[i][11] = IDENTIFIER;
	transitionTable[i][12] = IDENTIFIER;
	transitionTable[i][13] = IDENTIFIER;
	transitionTable[i][14] = IDENTIFIER;
	transitionTable[i][15] = IDENTIFIER;
	transitionTable[i][16] = IDENTIFIER;
	transitionTable[i][17] = IDENTIFIER;
	transitionTable[i][18] = IDENTIFIER;
	transitionTable[i][19] = IDENTIFIER;
	transitionTable[i][20] = IDENTIFIER;
	transitionTable[i][21] = IDENTIFIER;
	transitionTable[i][22] = IDENTIFIER;
	transitionTable[i][23] = IDENTIFIER;
	transitionTable[i][24] = IDENTIFIER;
	transitionTable[i][25] = IDENTIFIER;
	transitionTable[i][26] = TOKEN;
	transitionTable[i][27] = TOKEN;
	transitionTable[i][28] = TOKEN;
	transitionTable[i][29] = TOKEN;
	transitionTable[i][30] = TOKEN;
	transitionTable[i][31] = TOKEN;
	transitionTable[i][32] = TOKEN;
	transitionTable[i][33] = TOKEN;
	transitionTable[i][34] = TOKEN;

	// WRITE_SMALL_2
	i = 31;
	transitionTable[i][0]  = IDENTIFIER;
	transitionTable[i][1]  = IDENTIFIER;
	transitionTable[i][2]  = IDENTIFIER;
	transitionTable[i][3]  = IDENTIFIER;
	transitionTable[i][4]  = IDENTIFIER;
	transitionTable[i][5]  = IDENTIFIER;
	transitionTable[i][6]  = IDENTIFIER;
	transitionTable[i][7]  = IDENTIFIER;
	transitionTable[i][8]  = IDENTIFIER;
	transitionTable[i][9]  = IDENTIFIER;
	transitionTable[i][10] = IDENTIFIER;
	transitionTable[i][11] = IDENTIFIER;
	transitionTable[i][12] = IDENTIFIER;
	transitionTable[i][13] = IDENTIFIER;
	transitionTable[i][14] = IDENTIFIER;
	transitionTable[i][15] = IDENTIFIER;
	transitionTable[i][16] = IDENTIFIER;
	transitionTable[i][17] = IDENTIFIER;
	transitionTable[i][18] = WRITE_SMALL_3;
	transitionTable[i][19] = IDENTIFIER;
	transitionTable[i][20] = IDENTIFIER;
	transitionTable[i][21] = IDENTIFIER;
	transitionTable[i][22] = IDENTIFIER;
	transitionTable[i][23] = IDENTIFIER;
	transitionTable[i][24] = IDENTIFIER;
	transitionTable[i][25] = IDENTIFIER;
	transitionTable[i][26] = TOKEN;
	transitionTable[i][27] = TOKEN;
	transitionTable[i][28] = TOKEN;
	transitionTable[i][29] = TOKEN;
	transitionTable[i][30] = TOKEN;
	transitionTable[i][31] = TOKEN;
	transitionTable[i][32] = TOKEN;
	transitionTable[i][33] = TOKEN;
	transitionTable[i][34] = TOKEN;

	// WRITE_SMALL_3
	i = 32;
	transitionTable[i][0]  = IDENTIFIER;
	transitionTable[i][1]  = IDENTIFIER;
	transitionTable[i][2]  = IDENTIFIER;
	transitionTable[i][3]  = IDENTIFIER;
	transitionTable[i][4]  = IDENTIFIER;
	transitionTable[i][5]  = IDENTIFIER;
	transitionTable[i][6]  = IDENTIFIER;
	transitionTable[i][7]  = WRITE;
	transitionTable[i][8]  = IDENTIFIER;
	transitionTable[i][9]  = IDENTIFIER;
	transitionTable[i][10] = IDENTIFIER;
	transitionTable[i][11] = IDENTIFIER;
	transitionTable[i][12] = IDENTIFIER;
	transitionTable[i][13] = IDENTIFIER;
	transitionTable[i][14] = IDENTIFIER;
	transitionTable[i][15] = IDENTIFIER;
	transitionTable[i][16] = IDENTIFIER;
	transitionTable[i][17] = IDENTIFIER;
	transitionTable[i][18] = IDENTIFIER;
	transitionTable[i][19] = IDENTIFIER;
	transitionTable[i][20] = IDENTIFIER;
	transitionTable[i][21] = IDENTIFIER;
	transitionTable[i][22] = IDENTIFIER;
	transitionTable[i][23] = IDENTIFIER;
	transitionTable[i][24] = IDENTIFIER;
	transitionTable[i][25] = IDENTIFIER;
	transitionTable[i][26] = TOKEN;
	transitionTable[i][27] = TOKEN;
	transitionTable[i][28] = TOKEN;
	transitionTable[i][29] = TOKEN;
	transitionTable[i][30] = TOKEN;
	transitionTable[i][31] = TOKEN;
	transitionTable[i][32] = TOKEN;
	transitionTable[i][33] = TOKEN;
	transitionTable[i][34] = TOKEN;

	// WRITE_CAPITAL_1
	i = 33;
	transitionTable[i][0]  = IDENTIFIER;
	transitionTable[i][1]  = IDENTIFIER;
	transitionTable[i][2]  = IDENTIFIER;
	transitionTable[i][3]  = IDENTIFIER;
	transitionTable[i][4]  = IDENTIFIER;
	transitionTable[i][5]  = IDENTIFIER;
	transitionTable[i][6]  = IDENTIFIER;
	transitionTable[i][7]  = IDENTIFIER;
	transitionTable[i][8]  = WRITE_CAPITAL_2;
	transitionTable[i][9]  = IDENTIFIER;
	transitionTable[i][10] = IDENTIFIER;
	transitionTable[i][11] = IDENTIFIER;
	transitionTable[i][12] = IDENTIFIER;
	transitionTable[i][13] = IDENTIFIER;
	transitionTable[i][14] = IDENTIFIER;
	transitionTable[i][15] = IDENTIFIER;
	transitionTable[i][16] = IDENTIFIER;
	transitionTable[i][17] = IDENTIFIER;
	transitionTable[i][18] = IDENTIFIER;
	transitionTable[i][19] = IDENTIFIER;
	transitionTable[i][20] = IDENTIFIER;
	transitionTable[i][21] = IDENTIFIER;
	transitionTable[i][22] = IDENTIFIER;
	transitionTable[i][23] = IDENTIFIER;
	transitionTable[i][24] = IDENTIFIER;
	transitionTable[i][25] = IDENTIFIER;
	transitionTable[i][26] = TOKEN;
	transitionTable[i][27] = TOKEN;
	transitionTable[i][28] = TOKEN;
	transitionTable[i][29] = TOKEN;
	transitionTable[i][30] = TOKEN;
	transitionTable[i][31] = TOKEN;
	transitionTable[i][32] = TOKEN;
	transitionTable[i][33] = TOKEN;
	transitionTable[i][34] = TOKEN;

	// WRITE_CAPITAL_2
	i = 34;
	transitionTable[i][0]  = IDENTIFIER;
	transitionTable[i][1]  = IDENTIFIER;
	transitionTable[i][2]  = IDENTIFIER;
	transitionTable[i][3]  = IDENTIFIER;
	transitionTable[i][4]  = IDENTIFIER;
	transitionTable[i][5]  = IDENTIFIER;
	transitionTable[i][6]  = IDENTIFIER;
	transitionTable[i][7]  = IDENTIFIER;
	transitionTable[i][8]  = IDENTIFIER;
	transitionTable[i][9]  = IDENTIFIER;
	transitionTable[i][10] = IDENTIFIER;
	transitionTable[i][11] = IDENTIFIER;
	transitionTable[i][12] = IDENTIFIER;
	transitionTable[i][13] = IDENTIFIER;
	transitionTable[i][14] = IDENTIFIER;
	transitionTable[i][15] = IDENTIFIER;
	transitionTable[i][16] = IDENTIFIER;
	transitionTable[i][17] = IDENTIFIER;
	transitionTable[i][18] = IDENTIFIER;
	transitionTable[i][19] = IDENTIFIER;
	transitionTable[i][20] = IDENTIFIER;
	transitionTable[i][21] = IDENTIFIER;
	transitionTable[i][22] = IDENTIFIER;
	transitionTable[i][23] = IDENTIFIER;
	transitionTable[i][24] = WRITE_CAPITAL_3;
	transitionTable[i][25] = IDENTIFIER;
	transitionTable[i][26] = TOKEN;
	transitionTable[i][27] = TOKEN;
	transitionTable[i][28] = TOKEN;
	transitionTable[i][29] = TOKEN;
	transitionTable[i][30] = TOKEN;
	transitionTable[i][31] = TOKEN;
	transitionTable[i][32] = TOKEN;
	transitionTable[i][33] = TOKEN;
	transitionTable[i][34] = TOKEN;


	// WRITE_CAPITAL_3
	i = 35;
	transitionTable[i][0]  = IDENTIFIER;
	transitionTable[i][1]  = IDENTIFIER;
	transitionTable[i][2]  = IDENTIFIER;
	transitionTable[i][3]  = IDENTIFIER;
	transitionTable[i][4]  = IDENTIFIER;
	transitionTable[i][5]  = IDENTIFIER;
	transitionTable[i][6]  = IDENTIFIER;
	transitionTable[i][7]  = IDENTIFIER;
	transitionTable[i][8]  = IDENTIFIER;
	transitionTable[i][9]  = IDENTIFIER;
	transitionTable[i][10] = IDENTIFIER;
	transitionTable[i][11] = IDENTIFIER;
	transitionTable[i][12] = IDENTIFIER;
	transitionTable[i][13] = WRITE;
	transitionTable[i][14] = IDENTIFIER;
	transitionTable[i][15] = IDENTIFIER;
	transitionTable[i][16] = IDENTIFIER;
	transitionTable[i][17] = IDENTIFIER;
	transitionTable[i][18] = IDENTIFIER;
	transitionTable[i][19] = IDENTIFIER;
	transitionTable[i][20] = IDENTIFIER;
	transitionTable[i][21] = IDENTIFIER;
	transitionTable[i][22] = IDENTIFIER;
	transitionTable[i][23] = IDENTIFIER;
	transitionTable[i][24] = IDENTIFIER;
	transitionTable[i][25] = IDENTIFIER;
	transitionTable[i][26] = TOKEN;
	transitionTable[i][27] = TOKEN;
	transitionTable[i][28] = TOKEN;
	transitionTable[i][29] = TOKEN;
	transitionTable[i][30] = TOKEN;
	transitionTable[i][31] = TOKEN;
	transitionTable[i][32] = TOKEN;
	transitionTable[i][33] = TOKEN;
	transitionTable[i][34] = TOKEN;

	// WRTIE
	i = 36;
	transitionTable[i][0]  = IDENTIFIER;
	transitionTable[i][1]  = IDENTIFIER;
	transitionTable[i][2]  = IDENTIFIER;
	transitionTable[i][3]  = IDENTIFIER;
	transitionTable[i][4]  = IDENTIFIER;
	transitionTable[i][5]  = IDENTIFIER;
	transitionTable[i][6]  = IDENTIFIER;
	transitionTable[i][7]  = IDENTIFIER;
	transitionTable[i][8]  = IDENTIFIER;
	transitionTable[i][9]  = IDENTIFIER;
	transitionTable[i][10] = IDENTIFIER;
	transitionTable[i][11] = IDENTIFIER;
	transitionTable[i][12] = IDENTIFIER;
	transitionTable[i][13] = IDENTIFIER;
	transitionTable[i][14] = IDENTIFIER;
	transitionTable[i][15] = IDENTIFIER;
	transitionTable[i][16] = IDENTIFIER;
	transitionTable[i][17] = IDENTIFIER;
	transitionTable[i][18] = IDENTIFIER;
	transitionTable[i][19] = IDENTIFIER;
	transitionTable[i][20] = IDENTIFIER;
	transitionTable[i][21] = IDENTIFIER;
	transitionTable[i][22] = IDENTIFIER;
	transitionTable[i][23] = IDENTIFIER;
	transitionTable[i][24] = IDENTIFIER;
	transitionTable[i][25] = IDENTIFIER;
	transitionTable[i][26] = TOKEN;
	transitionTable[i][27] = TOKEN;
	transitionTable[i][28] = TOKEN;
	transitionTable[i][29] = TOKEN;
	transitionTable[i][30] = TOKEN;
	transitionTable[i][31] = TOKEN;
	transitionTable[i][32] = TOKEN;
	transitionTable[i][33] = TOKEN;
	transitionTable[i][34] = TOKEN;

	// ELSE_SMALL_1
	i = 37;
	transitionTable[i][0]  = IDENTIFIER;
	transitionTable[i][1]  = IDENTIFIER;
	transitionTable[i][2]  = IDENTIFIER;
	transitionTable[i][3]  = IDENTIFIER;
	transitionTable[i][4]  = IDENTIFIER;
	transitionTable[i][5]  = IDENTIFIER;
	transitionTable[i][6]  = IDENTIFIER;
	transitionTable[i][7]  = IDENTIFIER;
	transitionTable[i][8]  = ELSE_SMALL_2;
	transitionTable[i][9]  = IDENTIFIER;
	transitionTable[i][10] = IDENTIFIER;
	transitionTable[i][11] = IDENTIFIER;
	transitionTable[i][12] = IDENTIFIER;
	transitionTable[i][13] = IDENTIFIER;
	transitionTable[i][14] = IDENTIFIER;
	transitionTable[i][15] = IDENTIFIER;
	transitionTable[i][16] = IDENTIFIER;
	transitionTable[i][17] = IDENTIFIER;
	transitionTable[i][18] = IDENTIFIER;
	transitionTable[i][19] = IDENTIFIER;
	transitionTable[i][20] = IDENTIFIER;
	transitionTable[i][21] = IDENTIFIER;
	transitionTable[i][22] = IDENTIFIER;
	transitionTable[i][23] = IDENTIFIER;
	transitionTable[i][24] = IDENTIFIER;
	transitionTable[i][25] = IDENTIFIER;
	transitionTable[i][26] = TOKEN;
	transitionTable[i][27] = TOKEN;
	transitionTable[i][28] = TOKEN;
	transitionTable[i][29] = TOKEN;
	transitionTable[i][30] = TOKEN;
	transitionTable[i][31] = TOKEN;
	transitionTable[i][32] = TOKEN;
	transitionTable[i][33] = TOKEN;
	transitionTable[i][34] = TOKEN;

	// ELSE_SMALL_2
	i = 38;
	transitionTable[i][0]  = IDENTIFIER;
	transitionTable[i][1]  = IDENTIFIER;
	transitionTable[i][2]  = IDENTIFIER;
	transitionTable[i][3]  = IDENTIFIER;
	transitionTable[i][4]  = IDENTIFIER;
	transitionTable[i][5]  = IDENTIFIER;
	transitionTable[i][6]  = IDENTIFIER;
	transitionTable[i][7]  = IDENTIFIER;
	transitionTable[i][8]  = IDENTIFIER;
	transitionTable[i][9]  = IDENTIFIER;
	transitionTable[i][10] = IDENTIFIER;
	transitionTable[i][11] = IDENTIFIER;
	transitionTable[i][12] = IDENTIFIER;
	transitionTable[i][13] = IDENTIFIER;
	transitionTable[i][14] = IDENTIFIER;
	transitionTable[i][15] = IDENTIFIER;
	transitionTable[i][16] = IDENTIFIER;
	transitionTable[i][17] = IDENTIFIER;
	transitionTable[i][18] = IDENTIFIER;
	transitionTable[i][19] = ELSE_SMALL_3;
	transitionTable[i][20] = IDENTIFIER;
	transitionTable[i][21] = IDENTIFIER;
	transitionTable[i][22] = IDENTIFIER;
	transitionTable[i][23] = IDENTIFIER;
	transitionTable[i][24] = IDENTIFIER;
	transitionTable[i][25] = IDENTIFIER;
	transitionTable[i][26] = TOKEN;
	transitionTable[i][27] = TOKEN;
	transitionTable[i][28] = TOKEN;
	transitionTable[i][29] = TOKEN;
	transitionTable[i][30] = TOKEN;
	transitionTable[i][31] = TOKEN;
	transitionTable[i][32] = TOKEN;
	transitionTable[i][33] = TOKEN;
	transitionTable[i][34] = TOKEN;

	// ELSE_SMALL_3
	i = 39;
	transitionTable[i][0]  = IDENTIFIER;
	transitionTable[i][1]  = IDENTIFIER;
	transitionTable[i][2]  = IDENTIFIER;
	transitionTable[i][3]  = IDENTIFIER;
	transitionTable[i][4]  = IDENTIFIER;
	transitionTable[i][5]  = IDENTIFIER;
	transitionTable[i][6]  = IDENTIFIER;
	transitionTable[i][7]  = ELSE;
	transitionTable[i][8]  = IDENTIFIER;
	transitionTable[i][9]  = IDENTIFIER;
	transitionTable[i][10] = IDENTIFIER;
	transitionTable[i][11] = IDENTIFIER;
	transitionTable[i][12] = IDENTIFIER;
	transitionTable[i][13] = IDENTIFIER;
	transitionTable[i][14] = IDENTIFIER;
	transitionTable[i][15] = IDENTIFIER;
	transitionTable[i][16] = IDENTIFIER;
	transitionTable[i][17] = IDENTIFIER;
	transitionTable[i][18] = IDENTIFIER;
	transitionTable[i][19] = IDENTIFIER;
	transitionTable[i][20] = IDENTIFIER;
	transitionTable[i][21] = IDENTIFIER;
	transitionTable[i][22] = IDENTIFIER;
	transitionTable[i][23] = IDENTIFIER;
	transitionTable[i][24] = IDENTIFIER;
	transitionTable[i][25] = IDENTIFIER;
	transitionTable[i][26] = TOKEN;
	transitionTable[i][27] = TOKEN;
	transitionTable[i][28] = TOKEN;
	transitionTable[i][29] = TOKEN;
	transitionTable[i][30] = TOKEN;
	transitionTable[i][31] = TOKEN;
	transitionTable[i][32] = TOKEN;
	transitionTable[i][33] = TOKEN;
	transitionTable[i][34] = TOKEN;

	// ELSE_CAPITAL_1
	i = 40;
	transitionTable[i][0]  = IDENTIFIER;
	transitionTable[i][1]  = IDENTIFIER;
	transitionTable[i][2]  = IDENTIFIER;
	transitionTable[i][3]  = IDENTIFIER;
	transitionTable[i][4]  = IDENTIFIER;
	transitionTable[i][5]  = IDENTIFIER;
	transitionTable[i][6]  = IDENTIFIER;
	transitionTable[i][7]  = IDENTIFIER;
	transitionTable[i][8]  = IDENTIFIER;
	transitionTable[i][9]  = IDENTIFIER;
	transitionTable[i][10] = IDENTIFIER;
	transitionTable[i][11] = IDENTIFIER;
	transitionTable[i][12] = ELSE_CAPITAL_2;
	transitionTable[i][13] = IDENTIFIER;
	transitionTable[i][14] = IDENTIFIER;
	transitionTable[i][15] = IDENTIFIER;
	transitionTable[i][16] = IDENTIFIER;
	transitionTable[i][17] = IDENTIFIER;
	transitionTable[i][18] = IDENTIFIER;
	transitionTable[i][19] = IDENTIFIER;
	transitionTable[i][20] = IDENTIFIER;
	transitionTable[i][21] = IDENTIFIER;
	transitionTable[i][22] = IDENTIFIER;
	transitionTable[i][23] = IDENTIFIER;
	transitionTable[i][24] = IDENTIFIER;
	transitionTable[i][25] = IDENTIFIER;
	transitionTable[i][26] = TOKEN;
	transitionTable[i][27] = TOKEN;
	transitionTable[i][28] = TOKEN;
	transitionTable[i][29] = TOKEN;
	transitionTable[i][30] = TOKEN;
	transitionTable[i][31] = TOKEN;
	transitionTable[i][32] = TOKEN;
	transitionTable[i][33] = TOKEN;
	transitionTable[i][34] = TOKEN;

	// ELSE_CAPITAL_2
	i = 41;
	transitionTable[i][0]  = IDENTIFIER;
	transitionTable[i][1]  = IDENTIFIER;
	transitionTable[i][2]  = IDENTIFIER;
	transitionTable[i][3]  = IDENTIFIER;
	transitionTable[i][4]  = IDENTIFIER;
	transitionTable[i][5]  = IDENTIFIER;
	transitionTable[i][6]  = IDENTIFIER;
	transitionTable[i][7]  = IDENTIFIER;
	transitionTable[i][8]  = IDENTIFIER;
	transitionTable[i][9]  = IDENTIFIER;
	transitionTable[i][10] = IDENTIFIER;
	transitionTable[i][11] = IDENTIFIER;
	transitionTable[i][12] = IDENTIFIER;
	transitionTable[i][13] = IDENTIFIER;
	transitionTable[i][14] = IDENTIFIER;
	transitionTable[i][15] = IDENTIFIER;
	transitionTable[i][16] = IDENTIFIER;
	transitionTable[i][17] = IDENTIFIER;
	transitionTable[i][18] = IDENTIFIER;
	transitionTable[i][19] = IDENTIFIER;
	transitionTable[i][20] = IDENTIFIER;
	transitionTable[i][21] = IDENTIFIER;
	transitionTable[i][22] = IDENTIFIER;
	transitionTable[i][23] = IDENTIFIER;
	transitionTable[i][24] = IDENTIFIER;
	transitionTable[i][25] = ELSE_CAPITAL_3;
	transitionTable[i][26] = TOKEN;
	transitionTable[i][27] = TOKEN;
	transitionTable[i][28] = TOKEN;
	transitionTable[i][29] = TOKEN;
	transitionTable[i][30] = TOKEN;
	transitionTable[i][31] = TOKEN;
	transitionTable[i][32] = TOKEN;
	transitionTable[i][33] = TOKEN;
	transitionTable[i][34] = TOKEN;

	// ELSE_CAPITAL_3
	i = 42;
	transitionTable[i][0]  = IDENTIFIER;
	transitionTable[i][1]  = IDENTIFIER;
	transitionTable[i][2]  = IDENTIFIER;
	transitionTable[i][3]  = IDENTIFIER;
	transitionTable[i][4]  = IDENTIFIER;
	transitionTable[i][5]  = IDENTIFIER;
	transitionTable[i][6]  = IDENTIFIER;
	transitionTable[i][7]  = IDENTIFIER;
	transitionTable[i][8]  = IDENTIFIER;
	transitionTable[i][9]  = IDENTIFIER;
	transitionTable[i][10] = IDENTIFIER;
	transitionTable[i][11] = IDENTIFIER;
	transitionTable[i][12] = IDENTIFIER;
	transitionTable[i][13] = ELSE;
	transitionTable[i][14] = IDENTIFIER;
	transitionTable[i][15] = IDENTIFIER;
	transitionTable[i][16] = IDENTIFIER;
	transitionTable[i][17] = IDENTIFIER;
	transitionTable[i][18] = IDENTIFIER;
	transitionTable[i][19] = IDENTIFIER;
	transitionTable[i][20] = IDENTIFIER;
	transitionTable[i][21] = IDENTIFIER;
	transitionTable[i][22] = IDENTIFIER;
	transitionTable[i][23] = IDENTIFIER;
	transitionTable[i][24] = IDENTIFIER;
	transitionTable[i][25] = IDENTIFIER;
	transitionTable[i][26] = TOKEN;
	transitionTable[i][27] = TOKEN;
	transitionTable[i][28] = TOKEN;
	transitionTable[i][29] = TOKEN;
	transitionTable[i][30] = TOKEN;
	transitionTable[i][31] = TOKEN;
	transitionTable[i][32] = TOKEN;
	transitionTable[i][33] = TOKEN;
	transitionTable[i][34] = TOKEN;

	// ELSE
	i = 43;
	transitionTable[i][0]  = IDENTIFIER;
	transitionTable[i][1]  = IDENTIFIER;
	transitionTable[i][2]  = IDENTIFIER;
	transitionTable[i][3]  = IDENTIFIER;
	transitionTable[i][4]  = IDENTIFIER;
	transitionTable[i][5]  = IDENTIFIER;
	transitionTable[i][6]  = IDENTIFIER;
	transitionTable[i][7]  = IDENTIFIER;
	transitionTable[i][8]  = IDENTIFIER;
	transitionTable[i][9]  = IDENTIFIER;
	transitionTable[i][10] = IDENTIFIER;
	transitionTable[i][11] = IDENTIFIER;
	transitionTable[i][12] = IDENTIFIER;
	transitionTable[i][13] = IDENTIFIER;
	transitionTable[i][14] = IDENTIFIER;
	transitionTable[i][15] = IDENTIFIER;
	transitionTable[i][16] = IDENTIFIER;
	transitionTable[i][17] = IDENTIFIER;
	transitionTable[i][18] = IDENTIFIER;
	transitionTable[i][19] = IDENTIFIER;
	transitionTable[i][20] = IDENTIFIER;
	transitionTable[i][21] = IDENTIFIER;
	transitionTable[i][22] = IDENTIFIER;
	transitionTable[i][23] = IDENTIFIER;
	transitionTable[i][24] = IDENTIFIER;
	transitionTable[i][25] = IDENTIFIER;
	transitionTable[i][26] = TOKEN;
	transitionTable[i][27] = TOKEN;
	transitionTable[i][28] = TOKEN;
	transitionTable[i][29] = TOKEN;
	transitionTable[i][30] = TOKEN;
	transitionTable[i][31] = TOKEN;
	transitionTable[i][32] = TOKEN;
	transitionTable[i][33] = TOKEN;
	transitionTable[i][34] = TOKEN;

	// SIGN
	i = 44;
	transitionTable[i][0]  = TOKEN;
	transitionTable[i][1]  = TOKEN;
	transitionTable[i][2]  = TOKEN;
	transitionTable[i][3]  = TOKEN;
	transitionTable[i][4]  = TOKEN;
	transitionTable[i][5]  = TOKEN;
	transitionTable[i][6]  = TOKEN;
	transitionTable[i][7]  = TOKEN;
	transitionTable[i][8]  = TOKEN;
	transitionTable[i][9]  = TOKEN;
	transitionTable[i][10] = TOKEN;
	transitionTable[i][11] = TOKEN;
	transitionTable[i][12] = TOKEN;
	transitionTable[i][13] = TOKEN;
	transitionTable[i][14] = TOKEN;
	transitionTable[i][15] = TOKEN;
	transitionTable[i][16] = TOKEN;
	transitionTable[i][17] = TOKEN;
	transitionTable[i][18] = TOKEN;
	transitionTable[i][19] = TOKEN;
	transitionTable[i][20] = TOKEN;
	transitionTable[i][21] = TOKEN;
	transitionTable[i][22] = TOKEN;
	transitionTable[i][23] = TOKEN;
	transitionTable[i][24] = TOKEN;
	transitionTable[i][25] = TOKEN;
	transitionTable[i][26] = TOKEN;
	transitionTable[i][27] = TOKEN;
	transitionTable[i][28] = TOKEN;
	transitionTable[i][29] = TOKEN;
	transitionTable[i][30] = TOKEN;
	transitionTable[i][31] = BLANK;
	transitionTable[i][32] = LINE_BREAK;
	transitionTable[i][33] = TAB;
	transitionTable[i][34] = ERROR;

	// COLON
	i = 45;
	transitionTable[i][0]  = TOKEN;
	transitionTable[i][1]  = TOKEN;
	transitionTable[i][2]  = TOKEN;
	transitionTable[i][3]  = TOKEN;
	transitionTable[i][4]  = TOKEN;
	transitionTable[i][5]  = TOKEN;
	transitionTable[i][6]  = TOKEN;
	transitionTable[i][7]  = TOKEN;
	transitionTable[i][8]  = TOKEN;
	transitionTable[i][9]  = TOKEN;
	transitionTable[i][10] = TOKEN;
	transitionTable[i][11] = TOKEN;
	transitionTable[i][12] = TOKEN;
	transitionTable[i][13] = TOKEN;
	transitionTable[i][14] = TOKEN;
	transitionTable[i][15] = TOKEN;
	transitionTable[i][16] = TOKEN;
	transitionTable[i][17] = TOKEN;
	transitionTable[i][18] = TOKEN;
	transitionTable[i][19] = TOKEN;
	transitionTable[i][20] = TOKEN;
	transitionTable[i][21] = TOKEN;
	transitionTable[i][22] = TOKEN;
	transitionTable[i][23] = TOKEN;
	transitionTable[i][24] = TOKEN;
	transitionTable[i][25] = TOKEN;
	transitionTable[i][26] = TOKEN;
	transitionTable[i][27] = TOKEN;
	transitionTable[i][28] = COMMENT_1;
	transitionTable[i][29] = COLON_EQUAL;
	transitionTable[i][30] = TOKEN;
	transitionTable[i][31] = TOKEN;
	transitionTable[i][32] = TOKEN;
	transitionTable[i][33] = TOKEN;
	transitionTable[i][34] = TOKEN;


	// STAR
	i = 46;
	transitionTable[i][0]  = TOKEN;
	transitionTable[i][1]  = TOKEN;
	transitionTable[i][2]  = TOKEN;
	transitionTable[i][3]  = TOKEN;
	transitionTable[i][4]  = TOKEN;
	transitionTable[i][5]  = TOKEN;
	transitionTable[i][6]  = TOKEN;
	transitionTable[i][7]  = TOKEN;
	transitionTable[i][8]  = TOKEN;
	transitionTable[i][9]  = TOKEN;
	transitionTable[i][10] = TOKEN;
	transitionTable[i][11] = TOKEN;
	transitionTable[i][12] = TOKEN;
	transitionTable[i][13] = TOKEN;
	transitionTable[i][14] = TOKEN;
	transitionTable[i][15] = TOKEN;
	transitionTable[i][16] = TOKEN;
	transitionTable[i][17] = TOKEN;
	transitionTable[i][18] = TOKEN;
	transitionTable[i][19] = TOKEN;
	transitionTable[i][20] = TOKEN;
	transitionTable[i][21] = TOKEN;
	transitionTable[i][22] = TOKEN;
	transitionTable[i][23] = TOKEN;
	transitionTable[i][24] = TOKEN;
	transitionTable[i][25] = TOKEN;
	transitionTable[i][26] = TOKEN;
	transitionTable[i][27] = COMMENT_1;
	transitionTable[i][28] = TOKEN;
	transitionTable[i][29] = TOKEN;
	transitionTable[i][30] = TOKEN;
	transitionTable[i][31] = BLANK;
	transitionTable[i][32] = LINE_BREAK;
	transitionTable[i][33] = TAB;
	transitionTable[i][34] = ERROR;

	// EQUAL
	i = 47;
	transitionTable[i][0]  = TOKEN;
	transitionTable[i][1]  = TOKEN;
	transitionTable[i][2]  = TOKEN;
	transitionTable[i][3]  = TOKEN;
	transitionTable[i][4]  = TOKEN;
	transitionTable[i][5]  = TOKEN;
	transitionTable[i][6]  = TOKEN;
	transitionTable[i][7]  = TOKEN;
	transitionTable[i][8]  = TOKEN;
	transitionTable[i][9]  = TOKEN;
	transitionTable[i][10] = TOKEN;
	transitionTable[i][11] = TOKEN;
	transitionTable[i][12] = TOKEN;
	transitionTable[i][13] = TOKEN;
	transitionTable[i][14] = TOKEN;
	transitionTable[i][15] = TOKEN;
	transitionTable[i][16] = TOKEN;
	transitionTable[i][17] = TOKEN;
	transitionTable[i][18] = TOKEN;
	transitionTable[i][19] = TOKEN;
	transitionTable[i][20] = TOKEN;
	transitionTable[i][21] = TOKEN;
	transitionTable[i][22] = TOKEN;
	transitionTable[i][23] = TOKEN;
	transitionTable[i][24] = TOKEN;
	transitionTable[i][25] = TOKEN;
	transitionTable[i][26] = TOKEN;
	transitionTable[i][27] = COMPLEX_1;
	transitionTable[i][28] = TOKEN;
	transitionTable[i][29] = TOKEN;
	transitionTable[i][30] = TOKEN;
	transitionTable[i][31] = TOKEN;
	transitionTable[i][32] = TOKEN;
	transitionTable[i][33] = TOKEN;
	transitionTable[i][34] = TOKEN;

	// AND_1
	i = 48;
	transitionTable[i][0]  = ERROR;
	transitionTable[i][1]  = ERROR;
	transitionTable[i][2]  = ERROR;
	transitionTable[i][3]  = ERROR;
	transitionTable[i][4]  = ERROR;
	transitionTable[i][5]  = ERROR;
	transitionTable[i][6]  = ERROR;
	transitionTable[i][7]  = ERROR;
	transitionTable[i][8]  = ERROR;
	transitionTable[i][9]  = ERROR;
	transitionTable[i][10] = ERROR;
	transitionTable[i][11] = ERROR;
	transitionTable[i][12] = ERROR;
	transitionTable[i][13] = ERROR;
	transitionTable[i][14] = ERROR;
	transitionTable[i][15] = ERROR;
	transitionTable[i][16] = ERROR;
	transitionTable[i][17] = ERROR;
	transitionTable[i][18] = ERROR;
	transitionTable[i][19] = ERROR;
	transitionTable[i][20] = ERROR;
	transitionTable[i][21] = ERROR;
	transitionTable[i][22] = ERROR;
	transitionTable[i][23] = ERROR;
	transitionTable[i][24] = ERROR;
	transitionTable[i][25] = ERROR;
	transitionTable[i][26] = ERROR;
	transitionTable[i][27] = ERROR;
	transitionTable[i][28] = ERROR;
	transitionTable[i][29] = ERROR;
	transitionTable[i][30] = AND;
	transitionTable[i][31] = ERROR;
	transitionTable[i][32] = ERROR;
	transitionTable[i][33] = ERROR;
	transitionTable[i][34] = ERROR;

	// AND
	i = 49;
	transitionTable[i][0]  = TOKEN;
	transitionTable[i][1]  = TOKEN;
	transitionTable[i][2]  = TOKEN;
	transitionTable[i][3]  = TOKEN;
	transitionTable[i][4]  = TOKEN;
	transitionTable[i][5]  = TOKEN;
	transitionTable[i][6]  = TOKEN;
	transitionTable[i][7]  = TOKEN;
	transitionTable[i][8]  = TOKEN;
	transitionTable[i][9]  = TOKEN;
	transitionTable[i][10] = TOKEN;
	transitionTable[i][11] = TOKEN;
	transitionTable[i][12] = TOKEN;
	transitionTable[i][13] = TOKEN;
	transitionTable[i][14] = TOKEN;
	transitionTable[i][15] = TOKEN;
	transitionTable[i][16] = TOKEN;
	transitionTable[i][17] = TOKEN;
	transitionTable[i][18] = TOKEN;
	transitionTable[i][19] = TOKEN;
	transitionTable[i][20] = TOKEN;
	transitionTable[i][21] = TOKEN;
	transitionTable[i][22] = TOKEN;
	transitionTable[i][23] = TOKEN;
	transitionTable[i][24] = TOKEN;
	transitionTable[i][25] = TOKEN;
	transitionTable[i][26] = TOKEN;
	transitionTable[i][27] = TOKEN;
	transitionTable[i][28] = TOKEN;
	transitionTable[i][29] = TOKEN;
	transitionTable[i][30] = TOKEN;
	transitionTable[i][31] = BLANK;
	transitionTable[i][32] = LINE_BREAK;
	transitionTable[i][33] = TAB;
	transitionTable[i][34] = ERROR;

	// COMMENT_1
	i = 50;
	transitionTable[i][0]  = COMMENT_1;
	transitionTable[i][1]  = COMMENT_1;
	transitionTable[i][2]  = COMMENT_1;
	transitionTable[i][3]  = COMMENT_1;
	transitionTable[i][4]  = COMMENT_1;
	transitionTable[i][5]  = COMMENT_1;
	transitionTable[i][6]  = COMMENT_1;
	transitionTable[i][7]  = COMMENT_1;
	transitionTable[i][8]  = COMMENT_1;
	transitionTable[i][9]  = COMMENT_1;
	transitionTable[i][10] = COMMENT_1;
	transitionTable[i][11] = COMMENT_1;
	transitionTable[i][12] = COMMENT_1;
	transitionTable[i][13] = COMMENT_1;
	transitionTable[i][14] = COMMENT_1;
	transitionTable[i][15] = COMMENT_1;
	transitionTable[i][16] = COMMENT_1;
	transitionTable[i][17] = COMMENT_1;
	transitionTable[i][18] = COMMENT_1;
	transitionTable[i][19] = COMMENT_1;
	transitionTable[i][20] = COMMENT_1;
	transitionTable[i][21] = COMMENT_1;
	transitionTable[i][22] = COMMENT_1;
	transitionTable[i][23] = COMMENT_1;
	transitionTable[i][24] = COMMENT_1;
	transitionTable[i][25] = COMMENT_1;
	transitionTable[i][26] = COMMENT_1;
	transitionTable[i][27] = COMMENT_1;
	transitionTable[i][28] = COMMENT_2;
	transitionTable[i][29] = COMMENT_1;
	transitionTable[i][30] = COMMENT_1;
	transitionTable[i][31] = COMMENT_1;
	transitionTable[i][32] = COMMENT_1;
	transitionTable[i][33] = COMMENT_1;
	transitionTable[i][34] = COMMENT_1;

	// COMMENT_2
	i = 51;
	transitionTable[i][0]  = COMMENT_1;
	transitionTable[i][1]  = COMMENT_1;
	transitionTable[i][2]  = COMMENT_1;
	transitionTable[i][3]  = COMMENT_1;
	transitionTable[i][4]  = COMMENT_1;
	transitionTable[i][5]  = COMMENT_1;
	transitionTable[i][6]  = COMMENT_1;
	transitionTable[i][7]  = COMMENT_1;
	transitionTable[i][8]  = COMMENT_1;
	transitionTable[i][9]  = COMMENT_1;
	transitionTable[i][10] = COMMENT_1;
	transitionTable[i][11] = COMMENT_1;
	transitionTable[i][12] = COMMENT_1;
	transitionTable[i][13] = COMMENT_1;
	transitionTable[i][14] = COMMENT_1;
	transitionTable[i][15] = COMMENT_1;
	transitionTable[i][16] = COMMENT_1;
	transitionTable[i][17] = COMMENT_1;
	transitionTable[i][18] = COMMENT_1;
	transitionTable[i][19] = COMMENT_1;
	transitionTable[i][20] = COMMENT_1;
	transitionTable[i][21] = COMMENT_1;
	transitionTable[i][22] = COMMENT_1;
	transitionTable[i][23] = COMMENT_1;
	transitionTable[i][24] = COMMENT_1;
	transitionTable[i][25] = COMMENT_1;
	transitionTable[i][26] = COMMENT_1;
	transitionTable[i][27] = TOKEN;
	transitionTable[i][28] = COMMENT_1;
	transitionTable[i][29] = COMMENT_1;
	transitionTable[i][30] = COMMENT_1;
	transitionTable[i][31] = COMMENT_1;
	transitionTable[i][32] = COMMENT_1;
	transitionTable[i][33] = COMMENT_1;
	transitionTable[i][34] = COMMENT_1;

	// COLON_EQUAL
	i = 52;
	transitionTable[i][0]  = TOKEN;
	transitionTable[i][1]  = TOKEN;
	transitionTable[i][2]  = TOKEN;
	transitionTable[i][3]  = TOKEN;
	transitionTable[i][4]  = TOKEN;
	transitionTable[i][5]  = TOKEN;
	transitionTable[i][6]  = TOKEN;
	transitionTable[i][7]  = TOKEN;
	transitionTable[i][8]  = TOKEN;
	transitionTable[i][9]  = TOKEN;
	transitionTable[i][10] = TOKEN;
	transitionTable[i][11] = TOKEN;
	transitionTable[i][12] = TOKEN;
	transitionTable[i][13] = TOKEN;
	transitionTable[i][14] = TOKEN;
	transitionTable[i][15] = TOKEN;
	transitionTable[i][16] = TOKEN;
	transitionTable[i][17] = TOKEN;
	transitionTable[i][18] = TOKEN;
	transitionTable[i][19] = TOKEN;
	transitionTable[i][20] = TOKEN;
	transitionTable[i][21] = TOKEN;
	transitionTable[i][22] = TOKEN;
	transitionTable[i][23] = TOKEN;
	transitionTable[i][24] = TOKEN;
	transitionTable[i][25] = TOKEN;
	transitionTable[i][26] = TOKEN;
	transitionTable[i][27] = TOKEN;
	transitionTable[i][28] = TOKEN;
	transitionTable[i][29] = TOKEN;
	transitionTable[i][30] = TOKEN;
	transitionTable[i][31] = TOKEN;
	transitionTable[i][32] = TOKEN;
	transitionTable[i][33] = TOKEN;
	transitionTable[i][34] = TOKEN;


	// COMPLEX_1
	i = 53;
	transitionTable[i][0]  = CHECK;
	transitionTable[i][1]  = CHECK;
	transitionTable[i][2]  = CHECK;
	transitionTable[i][3]  = CHECK;
	transitionTable[i][4]  = CHECK;
	transitionTable[i][5]  = CHECK;
	transitionTable[i][6]  = CHECK;
	transitionTable[i][7]  = CHECK;
	transitionTable[i][8]  = CHECK;
	transitionTable[i][9]  = CHECK;
	transitionTable[i][10] = CHECK;
	transitionTable[i][11] = CHECK;
	transitionTable[i][12] = CHECK;
	transitionTable[i][13] = CHECK;
	transitionTable[i][14] = CHECK;
	transitionTable[i][15] = CHECK;
	transitionTable[i][16] = CHECK;
	transitionTable[i][17] = CHECK;
	transitionTable[i][18] = CHECK;
	transitionTable[i][19] = CHECK;
	transitionTable[i][20] = CHECK;
	transitionTable[i][21] = CHECK;
	transitionTable[i][22] = CHECK;
	transitionTable[i][23] = CHECK;
	transitionTable[i][24] = CHECK;
	transitionTable[i][25] = CHECK;
	transitionTable[i][26] = CHECK;
	transitionTable[i][27] = CHECK;
	transitionTable[i][28] = CHECK;
	transitionTable[i][29] = TOKEN;
	transitionTable[i][30] = CHECK;
	transitionTable[i][31] = CHECK;
	transitionTable[i][32] = CHECK;
	transitionTable[i][33] = CHECK;
	transitionTable[i][34] = CHECK;

	// CHECK
	i = 54;
	transitionTable[i][0]  = TOKEN;
	transitionTable[i][1]  = TOKEN;
	transitionTable[i][2]  = TOKEN;
	transitionTable[i][3]  = TOKEN;
	transitionTable[i][4]  = TOKEN;
	transitionTable[i][5]  = TOKEN;
	transitionTable[i][6]  = TOKEN;
	transitionTable[i][7]  = TOKEN;
	transitionTable[i][8]  = TOKEN;
	transitionTable[i][9]  = TOKEN;
	transitionTable[i][10] = TOKEN;
	transitionTable[i][11] = TOKEN;
	transitionTable[i][12] = TOKEN;
	transitionTable[i][13] = TOKEN;
	transitionTable[i][14] = TOKEN;
	transitionTable[i][15] = TOKEN;
	transitionTable[i][16] = TOKEN;
	transitionTable[i][17] = TOKEN;
	transitionTable[i][18] = TOKEN;
	transitionTable[i][19] = TOKEN;
	transitionTable[i][20] = TOKEN;
	transitionTable[i][21] = TOKEN;
	transitionTable[i][22] = TOKEN;
	transitionTable[i][23] = TOKEN;
	transitionTable[i][24] = TOKEN;
	transitionTable[i][25] = TOKEN;
	transitionTable[i][26] = TOKEN;
	transitionTable[i][27] = TOKEN;
	transitionTable[i][28] = TOKEN;
	transitionTable[i][29] = TOKEN;
	transitionTable[i][30] = TOKEN;
	transitionTable[i][31] = TOKEN;
	transitionTable[i][32] = TOKEN;
	transitionTable[i][33] = TOKEN;
	transitionTable[i][34] = TOKEN;
}
